### ISSUE TITLE
CF does not recover from a full shutdown

### ISSUE THREAD

**Issue by neilhwatson** [cloudfoundry/cf-release#1055]
We have a POC CF, v242, installed on a Vsphere host. During some power maintenance, Vsphere and all Bosh and CF vm's were shutdown. Afterward, when they were powered back on the following CF vm's were in a failed state:

1. Both uaa's
2. Both api's
3. Both hm9000's
4. Both loggregator's
5. Blobstore

Some debugging showed that the directory /var/vcap/sys/run/route_registrar/ did not exist on the failed hosts. We had to manually create the dir on each host and restart services via monit. But that still did not fix everything. One hm9000 vm continued to malfunction. Our last recourse was to redeploy all of CF and then any apps that were previously deployed.

We have repeated this behavior on multiple tests.

**Comment by Amit-PivotalLabs** [comment]
I suspect this issue is due to the fact that `route_registrar` does not create the `RUN_DIR` in its "ctl" script [[0](https://github.com/cloudfoundry-incubator/routing-release/blob/a059f53796889b834d1f63c9855f38c5c4aa41c8/jobs/route_registrar/templates/route_registrar_ctl.erb#L5-L28)], and only does so in its pre-start script [[1](https://github.com/cloudfoundry-incubator/routing-release/blob/a059f53796889b834d1f63c9855f38c5c4aa41c8/jobs/route_registrar/templates/pre-start#L9)] which probably doesn't get run by BOSH in the scenario you're describing.

I'll close out this issue and open one on the `routing-release` repo.
