### ISSUE TITLE
Failed to perform blobstore operation after three retries

### ISSUE THREAD

**Issue by arslanabbasi** [cloudfoundry/cf-release#1057]
Hi,

I have a successful CF deployment with OpenStack CPI. Following are the symptoms of the problem

1. Running "cf push" with an example program(fib-cpu) throws the following error
http://paste.ubuntu.com/23193642/

2. Blobstore internal_error.log shows that access is forbidden by rule. Output is given below
http://paste.ubuntu.com/23195378/

CF cli version: cf version 6.21.1+6fd3c9f-2016-08-10
Bosh: BOSH 1.3262.4.0

Let me know if any other information is required. Any help is greatly appreciated. Thanks

**Comment by jleavers** [comment]
Hi,

Do you have your subnet (e.g. 2.2.2.0/24) listed in the blobstore allow
directive?

blobstore.internal_access_rules:
  description: >-
    List of allow / deny rules for the blobstore internal server. Defaults
    to RFC 1918 Private Networks. Will be followed by 'deny all'. See
    http://nginx.org/en/docs/http/ngx_http_access_module.html for valid rules
  default:
    - "allow 10.0.0.0/8;"
    - "allow 172.16.0.0/12;"
    - "allow 192.168.0.0/16;"



On 18 September 2016 at 02:49:15, arslanabbasi (notifications@github.com)
wrote:

Hi,

I have a successful CF deployment with OpenStack CPI. Following are the
symptoms of the problem

   1.

   Running "cf push" with an example program(fib-cpu) throws the following
   error
   http://paste.ubuntu.com/23193642/
   2.

   Blobstore internal_error.log shows that access is forbidden by rule.
   Output is given below
   http://paste.ubuntu.com/23195378/

CF cli version: cf version 6.21.1+6fd3c9f-2016-08-10
Bosh: BOSH 1.3262.4.0

Let me know if any other information is required. Any help is greatly
appreciated. Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudfoundry/cf-release/issues/1057>, or mute the thread

**Comment by arslanabbasi** [comment]
Hi jleavers,

As you mentioned, adding the **two lines** solved the issue. For reference, a snippet from my cf-deployment.yml is given below. Thanks alot for the help!

`
properties:
..acceptance_tests: null
..app_domains:
..- cf.********.com
..app_ssh: null
..blobstore:
....**internal_access_rules:**
......**- "allow 2.2.2.0/24;**"

`
