### ISSUE TITLE
CF 233 - Failed to complile package statsite

### ISSUE THREAD

**Issue by sdheepa** [cloudfoundry/cf-release#1071]
I am using CF version 233 to deploy cloud foundry (using bosh) and am running into a compilation issue that I have not run into before. The full error is attached as a text file. Has anyone run into this before and is there a solution for this problem? Appreciate any help!

 Failed compiling packages > statsite/abf4980a9e439c5a9242ce8cceeb3b071e5ccfa8: Action Failed get_task: Task 786f1e1e-ac9e-42c3-60eb-208755dbcb34 result: Compiling package statsite: Running packaging script: Command exited with 1; Truncated stdout: Suggested packages:
  python-genshi python-lxml python-distribute python-distribute-doc
Recommended packages:
  python-dev-all

[CFcompilationError.txt](https://github.com/cloudfoundry-community/bosh-bootstrap/files/509244/CFcompilationError.txt)

**Comment by dsabeti** [comment]
@sdheepa It seems like it's failing to compile a package called `statsite`, which I'm unfamiliar with. Is this just a deployment of cf-release, or is there another release that you're deploying with it? Could you post your deployment manifest **and make sure to redact any sensitive data such as passwords and private keys**?

**Comment by sdheepa** [comment]
Actually you are right that this is not just cf being deployed, there are other releases in the yml. Statsite is coming from metricsrelay based on the yml which is failing to compile. If this is not the right forum please direct me to the forum where I should post this question. Attached is the deployment manifest yml.
[cf-template.txt](https://github.com/cloudfoundry/cf-release/files/509469/cf-template.txt)

**Comment by dsabeti** [comment]
Yeah, this repository is not really the right forum for this, since the issue pertains to a different release. I looked at your manifest to see which release contains the `statsite` package, but the name of the release is templatized:
```
- name: metrics
  version: <%= $metrics_release %>
```
Unfortunately, I can't direct you without knowing the name of that release. But if you can find the value of `metrics_release`, you could easily search github (or just Google it, for that matter) for the release name and ask for help there when you find the repo.

In the meantime, since CF is not implicated, I'm going to close the issue. Good luck!
