### ISSUE TITLE
Log helper does a lot of shelling out

### ISSUE THREAD

**Issue by mmb** [cloudfoundry/cf-release#1077]
Why does the log helper in

src/common/utils.sh

need to append a timestamp? Shouldn't syslog do that?

It shells out to awk which shells out to echo which shells out to date for every log line.

**Comment by dsabeti** [comment]
I realize this issue is pretty out of date, but I wanted to leave an update here in case anyone else if following along.

On top of planning to deprecate cf-release soon, we're also trying to deprecate these log helpers in all of the component CF releases. Instead, we're going to move forward to [syslog-release](https://github.com/cloudfoundry/syslog-release).

I'm going to close this issue, but feel free to re-open it if you have more questions about the log helpers.
