### ISSUE TITLE
With reference to ticket #1088

### ISSUE THREAD

**Issue by rahul221191** [cloudfoundry/cf-release#1097]
Hi,
For the ticket https://github.com/cloudfoundry/cf-release/issues/1088

There might be the case of failure of one postgreSQL.
Can't we just increase the instance count of postgresSQL from 1 to 2 ?
There might be some way to avoid single point of failure for postgreSQL?
Can you please suggest.

Thanks and Regards 
Rahul Kumar

**Comment by valeriap** [comment]
@rahul221191,

Cloud Foundry documentation recommends for the postgres_z job only 0 or 1 total instances, where 0 means that you use an external postgres database.
(see https://docs.cloudfoundry.org/concepts/high-availability.html)

This because the bosh postgres-release used in cf currently does not directly support high availability and backup and restore configurations.
If you deploy more instances, just one of them would be used. 

I agree with you that in a production environment resiliency is an aspect to consider.

The first option you have is to leverage an external postgreSQL service that provides these functionalities.
Otherwise you may build around the deployed nodes your custom solution.

I talk about custom solution because as said you cannot simply modify the yml and deploy.

First of all you should put in place backup and restore.
Secondly you should take care of configuring the nodes for high availability, of keeping this customization across bosh deployments, and of implementing your custom failover procedures.
Various tools are there to help managing replication/failover but as said they are not integrated with postgres-release and bosh. 

More info about postgreSQL resiliency can be found here:
https://www.postgresql.org/docs/9.4/static/high-availability.html
https://www.postgresql.org/docs/9.4/static/backup.html

Regards,
Valeria.

**Comment by rahul221191** [comment]
i will try to deploy external custom postgresql.
Thanks for the suggestion.

regards 
Rahul Kumar

**Comment by dsabeti** [comment]
Hi @rahul221191.

If you're looking for a highly available database for a production CF, you have a few options.

You could try to deploy the cf-mysql-release. You can ask them there for help with deploying MySQL as an HA database for Cloud Foundry components.
You could also use a third-party service like RDS. They have pretty good guarantees for availability.
In either case, once you know

the location -- either an IP address or a URL
the port of the database process
the admin credentials you can configure the cloud controller and UAA jobs to use that database.
