### ISSUE TITLE
An app instance may be registred on gorouter while evacuating

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cf-release#1133]
When a DEA is being evacuated all app instances should be unregistered before they receive TERM (which works as expected) and they should never be registered back (which can happen in certain cases). Please take a look at https://github.com/cloudfoundry/dea_ng/pull/203.

**Comment by JesseTAlford** [comment]
I'm not sure what you're looking for in opening an issue here, @giner. As you've identified, to the extent that this is an issue, it's an issue with the DEA. It looks like you have an ongoing conversation (and a pull request, though it looks like it needs tests) there.

How are you hoping opening this issue here will help?

**Comment by giner** [comment]
> How are you hoping opening this issue here will help?

Both the issue and the PR were closed quickly after submitting without thorough discussion. I just want to raise attention to this DEA issue and I'm not sure about any better way to do this.

**Comment by dsabeti** [comment]
Hey @giner. Thanks for bringing this up, but I think it's best if the conversation continues in the github issue you opened in the dea_ng repo. I've left a comment for you there.
