### ISSUE TITLE
upload bits ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')

### ISSUE THREAD

**Issue by harshalk91** [cloudfoundry/cf-release#1153]
I am trying to upload bits for an application through API using Python

```
import requests, json, argparse
from requests.packages.urllib3.exceptions import InsecureRequestWarning
# Disable Insecure Request Warning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

def upload_bits(api_url, api_token, app_guid, fileobj):
    print("I am inside upload_bits")
    response = requests.post(api_url + "/v2/apps/" + app_guid + "bits", verify=False, headers={'AUTHORIZATION': 'bearer ' + api_token, 'Content-Type': 'multipart/form-data', 'boundary': 'AaB03x'}, files={"archive": ("admin-ui.zip", fileobj)})
    print response.json(), response.status_code

if __name__ == "__main__":
try:
     ### Token Generation Code here ###

       fileobj = open("C:/Users/xxx/PycharmProjects/cf-api/admin-ui.zip", "rb")
       upload_bits(api_url, api_token, app_guid, fileobj)
except Exception as e:
        print e
```

I am getting the exception as 

`('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')`

I am using `cf-release 230`
```

API endpoint:   https://xxx.xxx.xxx.openstack.xxx.com
API version:    2.48.0
```

**Comment by dsabeti** [comment]
Hey @harshalk91. It seems to me that this issue is more relevant to the [Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng) specifically, since that component implements the API endpoint you're targeting. You'll have better luck opening this issue there.

I'd also point out two things:
1) Your CF version is pretty old, and it would probably help to upgrade to a more recent version
2) If there's any way to get more information about that failed request, it would help with troubleshooting. For example, can you get a similar failure with `curl` or `wget`? If so, you can use verbosity flags (like `curl -v`) to get more details about the failure.

**Comment by dsabeti** [comment]
Hi @harshalk91. I'm going to close this issue for lack of activity, but please feel free to re-open it if you still need help with this problem.
