### ISSUE TITLE
 syslog_drain_binder x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry/cf-release#1159]
Hi, 

I got this error ` x509 certificate signed by unknown authority` from `syslog_drain_binder` job when deploying the cf-release version 253.

Also, Could any one please tells me from where i should generate these below certificates. I assume from `cf-release/scripts/generate-cf-diego-certs`, however, i m not using diego. I use DEA instead.

`
mutual_tls:
         ca_cert: CC_MUTUAL_TLS_CA_CERT
         public_cert: CC_MUTUAL_TLS_PUBLIC_CERT
         private_key: CC_MUTUAL_TLS_PRIVATE_KEY

`

Thanks,
Fadhel

**Comment by dsabeti** [comment]
Hi @fghorbel.

Let me explain a little about how this works. Most of the certs created by the `generate-X-certs` scripts are used for mutual TLS between CF components. That means that both components must present their certificate to the other component, and both components must verify that the certificate was signed by a _**trusted Certificate Authority (CA)**._ They verify that signature by knowing the _**CA certificate**_.

Some components only talk with a few other components. For example, traffic controller, doppler, and metron communicate with each other, and nothing else. That's why [this script](https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-loggregator-certs#L45) signs those certificates with the `loggregator-ca`.

Other components talk with a larger set of other components. For example, the Cloud Controller communicates with a few of the Diego components (CC Bridge and the BBS), as well as some Loggregator components (the syslog drain binder). As a result, the certificates for the Cloud Controller, the CC Bridge, the Diego BBS, and the syslog drain binder must all be signed by the same CA -- the CA created by (you guessed correctly) `scripts/generate-cf-diego-certs`.

In some contexts, that CA is might be called the Cloud Controller CA; in some contexts, it might be called the [BBS CA](https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-loggregator-certs#L61). The reason the script is called `generate-cf-diego-certs` is that it's used by both CF and Diego (if you deploy it). It does, however, sign other certificates -- including the one for syslog drain binder.

So, to actually answer your questions:
1. `mutual_tls.ca_cert`, etc., are the certificates being generated by `scripts/generate-cf-diego-certs` -- even if you aren't using Diego you should use that script. 
2. The syslog_drain_binder cert must be signed by the same CA as you placed in `mutual_tls.ca_cert`. You can generate it by running `generate-loggregator-certs path/to/cf-diego-ca.crt path/to/cf-diego-ca.key`.

Let me know if that helps.

**Comment by fghorbel** [comment]
Hi,

Thank you for this great answer. I s very clear. 

Fadhel

**Comment by dsabeti** [comment]
Hey @fghorbel. Happy to help. I'm going to close the issue, but if you have problems with this in the future, take a look at [this doc](https://github.com/cloudfoundry/cf-release/blob/develop/on-tls-certificates.md).
