### ISSUE TITLE
Allow custom CATS artifacts directory

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/cf-release#1197]
cf-smoke-tests allow customising CATS artifacts directory: [here](https://github.com/cloudfoundry/cf-release/blob/master/jobs/smoke-tests/spec#L52-L53),  [here](https://github.com/cloudfoundry/cf-release/blob/master/jobs/smoke-tests/templates/config.json.erb#L21-L23) and [here](https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/config.go#L30)

But acceptance tests don't. [The code allows customising it](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/helpers/config/config_struct.go#L43) but the value is hardcoded in the template: [here](https://github.com/cloudfoundry/cf-release/blob/master/jobs/acceptance-tests/templates/config.json.erb#L8).

We don't run CATS in an errand so it's a bit akward to write to that place. Could we have the same behaviour as in smoke tests?

**Comment by dsabeti** [comment]
Hey @saliceti. 

cf-acceptance-tests is included in cf-release so that deployers to run the tests as a BOSH errand (a workflow we intended to deprecate in cf-deployment). Most file paths in a BOSH VM don't make sense to use (some, in fact, would cause problems with BOSH), so cf-release hard-codes the value to a sensible path in the `logs` directory, which is guaranteed to exist because of the other steps in the errand.

If you run the acceptance-tests as a concourse task or from your local machine, you should be able to choose an artifacts directory without any problems (let me know if that's not your experience with it). You [can provide an `artifacts_directory` entry to your integration_config.json](https://github.com/cloudfoundry/cf-acceptance-tests#capturing-test-output).

**Comment by saliceti** [comment]
Hi,

We run CATS in a pipeline. Using [config.json.erb from cf-release](https://github.com/cloudfoundry/cf-release/blob/master/jobs/acceptance-tests/templates/config.json.erb) is quite convenient as it picks the values from the manifest. Except for `artifacts_directory`.

Is there a reason to keep a different behaviour between smoke tests and acceptance tests?

**Comment by dsabeti** [comment]
The real reason not to make them the same is that we're on the path to deprecating cf-release (which will be replaced by [cf-deployment](https://github.com/cloudfoundry/cf-deployment)) as well as the CATs errand. (Smoke tests, on the other hand, will be supported as an errand long-term.)

As for using the config.json from cf-release, you could always update the artifacts directory as a post-processing step before running the CATs task.

**Comment by saliceti** [comment]
OK I've changed our code so we don't rely on the template anymore
Thanks
