### ISSUE TITLE
runner_z1/0 is not running after update. Review logs for failed jobs: warden, dea_next

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/cf-release#1209]
Updating instance runner_z1: runner_z1/6262f048-954a-4dff-b04e-f9818cab3dc0 (0) (canary) (00:10:45)
            L Error: 'runner_z1/0 (6262f048-954a-4dff-b04e-f9818cab3dc0)' is not running after update. Review logs for failed jobs: warden, dea_next

06:23:50 | Error: 'runner_z1/0 (6262f048-954a-4dff-b04e-f9818cab3dc0)' is not running after update. Review logs for failed jobs: warden, dea_next

runner_z1 logs:
please remove .txt.

[peracloud.runner_z1-20170609-062439-977279851.tgz.txt](https://github.com/cloudfoundry/cf-release/files/1063166/peracloud.runner_z1-20170609-062439-977279851.tgz.txt)

**Comment by dsabeti** [comment]
Hi @bxlkm. I took a look at the logs, and the issue is that you're deploying with an incompatible stemcell. You need to be using the 3312.X line. 

More importantly, however, support for the `runner` jobs ended a few weeks ago. You'll need to start deploying [Diego](https://github.com/cloudfoundry/diego-release) instead.

**Comment by dsabeti** [comment]
Hi @bxlkm. I'm going to close this issue due to inactivity, but feel free to close it if you need more help.
