### ISSUE TITLE
Wrong cname when generating Certificates for ETCD

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cf-release#1217]
Hi,
when generating the Certs for ETCD the `./scripts/generate-etcd-certs` my diego deployment fails because for cname database the name is `database.etcd.service.cf.internal` and not `database.cf-etcd.service.cf.internal`.

https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-etcd-certs#L18

Is this intended?

BR,
Johannes

**Comment by dsabeti** [comment]
Hey @jhiemer. This was always a confusing part of the CF architecture. The good news is that it's actually a deprecated architecture. Let me explain.

For a long time, there were actually _two_ etcd clusters in CF: one for Loggregator, and one for Diego. 

The etcd associated with Loggregator is deployed as part of cf-release, and _that_ etcd is what uses `scripts/generate-etcd-certs` in cf-release, as well as the CNAME `cf-etcd.service.cf.internal`.

The etcd associated with Diego was part of the diego-release, and [deployed as part of the database job](https://github.com/cloudfoundry/diego-release/blob/develop/manifest-generation/diego.yml#L1041-L1050). _This_ etcd cluster used the CNAME `etcd.service.cf.internal`, and used diego-release's own version of `scripts/generate-etcd-certs`.

However, using etcd as the backing datastore for Diego was deprecated about last fall. [This commit](https://github.com/cloudfoundry/diego-release/commit/5b46d9688c7eaa60faf9a4360815c550ca878236) marks the cutover for migrating from an etcd datastore to a SQL datastore, and you can even see [that it deletes the script for generating etcd certs](https://github.com/cloudfoundry/diego-release/commit/5b46d9688c7eaa60faf9a4360815c550ca878236#diff-cdffe837686dd90c3f1dd45feb5ff53c).

So, what I'd recommend for you is to use a SQL datastore for Diego rather than etcd. You can do this by providing the `-s` flag to the Diego manifest generation script, along with a spiff stub that sets [the correct SQL overrides](https://github.com/cloudfoundry/diego-release/blob/develop/manifest-generation/diego.yml#L626-L633).

Finally, I should make one last pitch: if you're deploying an environment for the first time, and this isn't for production use just yet, you may want to check out [cf-deployment](https://github.com/cloudfoundry/cf-deployment). The manifest provided there will soon replace the manifest generation scripts in cf-release, and the process of deploying in considerably simpler.

Hope that helped!

**Comment by jhiemer** [comment]
@dsabeti thanks a lot for this very detailed description. I now remember, the notice to the deprecation of etcd and it is really good you remembered me. Actually my deployment for diego already had the preparation with the SQL file, but I still deployed it with ETCD.

So if I am correct, I am going to deploy the database configuration for BBS now, against my endpoint and then:

1. I configure the database an the diego-sql.yml file accordingly
2. Deploy it
3. Transfer data from etcd to the SQL Backend (https://github.com/cloudfoundry/diego-release/blob/develop/docs/data-stores.md) 
4. Remove the etcd instance

Correct?

P.S. Regarding `cf-deployment`: This is an older deployment based on `cf-release` I am upgrading from v245 to v265. Afterwards, when `cf-deployment` is ready and stable, the next step would be the migration towards `cf-deployment`.

**Comment by dsabeti** [comment]
@jhiemer Yep, that's right. Good luck!

**Comment by dsabeti** [comment]
Hi @jhiemer. Any updates?

**Comment by jhiemer** [comment]
@dsabeti yes that fixed it!
