### ISSUE TITLE
Entry is getting created during cf a when the host is taken already 

### ISSUE THREAD

**Issue by gowrisankar22** [cloudfoundry/cf-release#1221]
Hi Colleagues,

When user is pushing an app with the same host which is already taken ideally it shouldnot create any entry during cf a.

C:\Users\XXX\Desktop\kibana-me-logs>cf p
Using manifest file C:\Users\XXX\Desktop\kibana-me-logs\manifest.yml

Creating app kibana in org XXX_trial / space dev as XXXX...
OK

Creating route XXXXXXXXXXXX...
OK

FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: kibana

C:\Users\XXX\Desktop\kibana-me-logs>cf a
Getting apps in org XXXX_trial / space dev as XXXX...
OK

name     requested state   instances   memory   disk   urls
kibana   stopped           0/1         128M     1G

BRs, gowrisankar

**Comment by dsabeti** [comment]
@gowrisankar22 This behavior is by design. Routes and Apps are separate concepts in Cloud Foundry, because you may want to bind several different routes to the same app. You may also want to "move" routes from app to another, for example, if you're performing a [blue-green deploy](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html).

For example, you could success push you app by adding the `--hostname` (or it's alias `-n`) to your `cf push` command, and get the app to run successfully.

**Comment by dsabeti** [comment]
Hi @gowrisankar22, I'm going to close the issue here due to inactivity, but feel free to re-open it if you have more questions.
