### ISSUE TITLE
CF api too slow

### ISSUE THREAD

**Issue by rahul221192** [cloudfoundry/cf-release#1255]
Hi Team ,

We are using cf release 271.
Our cf is working too slow.Even simple command like cf a or cf ssh or too slow.

Can you please tell us the possible causes of cf being too slow?

Note:-We have cf running on AWS .Instance type  of **api vm** is **m4.large**.When we do upgrade of cf and check our cloudwatch on AWS ,hits on api Vm increases drastically.Is vm size can be the possible cause for cf being to slow?

Thanks
Rahul Kumar

**Comment by dsabeti** [comment]
Hi @rahul221192, I would advise using tools like `htop` to understand what's causing the API to be slow. If you ssh onto the VM and run `htop`, you can see a) which resources (RAM or CPU) are the most constrained, and b) which process is using them. I'd also suggest comparing resource usage when the API is not serving any requests and when it's under some load.

I'll also loop in @zrob and @gerg for help diagnosing the issue.

**Comment by rahul221192** [comment]
i don't whether its normal or not .I ssh on api and used htop as you suggested.and i can see > 144 CPU utilization.
![screen shot 10-10-17 at 11 25 am 001](https://user-images.githubusercontent.com/16372337/31371481-af50d490-adae-11e7-97bc-c7bb6d834abf.PNG)

**Comment by Gerg** [comment]
@rahul221192 Slow API response times could be caused by many factors. Here are some tips that might help you debug your deployment:
- Check your DB utilization. If you DB is CPU or memory constrained, it will slow down everything. 
- CC emits [metrics](https://docs.cloudfoundry.org/running/all_metrics.html) that can help diagnose issues. One easy way to visualize these is to deploy the [prometheus release](https://github.com/cloudfoundry-community/prometheus-boshrelease) or use an external tool like DataDog.
- CC can be configured to emit New Relic metrics: https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=276#p=cc.newrelic

Good Luck!

**Comment by rahul221192** [comment]
@Gerg we got the issue ,There were too many request coming from prometheus by cf exporter.For now we stopped the cf-exporter and there is no lag and api vm is running fine.
Thanks for the help @Gerg @dsabeti
