### ISSUE TITLE
Running errand Pivotal Account Errand for Pivotal Elastic Runtime

### ISSUE THREAD

**Issue by sirjune** [cloudfoundry/cf-release#1262]
First, thank you for the help in  #1261.  I was able get past through that step and the next ones and figured out the error from the logs.  My apologies for coming back here again but been stuck at the step above. The other errands went OK . All errands are set to Default(when changed) except SmokeTest =ON(default).  I looked for errors and found  these (see attached file).  I'd appreciate if you any assistance to troubleshoot this.

thanks,
Sirjune

...
{  
             "description": "App has not finished staging",  
             "error_code": "CF-NotStaged",  
             "code": 170002  
           }  
...

...             
 FAILED  
           Error: unexpected end of JSON input  
...            

...          
Errand 'push-pivotal-account' completed with error (exit code 1)
...
[pcf_errand.txt](https://github.com/cloudfoundry/cf-release/files/1479308/pcf_errand.txt)

**Comment by dsabeti** [comment]
Hi @sirjune. It looks like the app is taking longer than 5 minutes to start up, and the CLI is timing out. You'll need to dig and see why it's taking so long to stage and/or start. You can run `cf logs --recent` to get more information.

Second, since you're seeing an issue with a Pivotal-specific errand, you should probably contact Pivotal Support. The errand you're asking about isn't anywhere in the OSS repos, so we don't know much about them.

**Comment by sirjune** [comment]
David,

Thank you for the response.  an overview, i am deploying pcf on vsphere. i have VM OpsManager and a VM Director.  I can ssh to the OpsManager and run bosh2 commands.  the "cf" CLI is not being found (or not installed in the OpsManager). i think cf CLI is on the Director. However, i cant figure out the username/password to login/ssh to the directory so i can run "cf" commands.

thanks,
sirjune

**Comment by dsabeti** [comment]
Hi @sirjune, best to get in touch with Pivotal support, as they'll be able to tell you how to use OpsManager to get a CLI, username/password, etc.

**Comment by sirjune** [comment]
Thanks David!  will chase Pivotal.
