### ISSUE TITLE
gorouter.logrotate.rotate and .size properties not in gorouter spec file

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cf-release#628]
The spec for gorouter is missing the properties for configuring log rotation.

properties:
  router.logrotate.rotate:
    description: "The number of log files to keep on the system."  
    default: 7
  router.logrotate.size:
    description: "The size at which the log file will be rotated."
    default: 2M

Jon Price
Intel Corp.

**Comment by dieucao** [comment]
@jmprice BOSH stemcells actually now completely controls the log rotation policy.  We have a bug [1] open to remove the custom configuration on gorouter because it does not work.
You can find in this chore [2] details on how it works by default on all bosh deployed vms.  We had asked @cppforlife to consider making the rotation policy job configurable but I don't see a story for that in his backlog.

[1] https://www.pivotaltracker.com/story/show/88751300
[2] https://www.pivotaltracker.com/story/show/88655850

**Comment by jmprice** [comment]
@dieucao I just made the change manually to our gorouter/config/logrotate.conf and the configuration is working.  It was rotating the logs at 2M and they are currently > 3M and growing.  After looking at it further it seems that the real issue is that the logrotate.conf.erb file isn't  pulling in the manifest properties correctly so they never get written to the logrotate.conf file.

Anyway, if you are going to remove the configuration entirely and have it default to the 50M size for all other log files, that would work for us.  2M is just too small to be useful.

-- Jon Price

**Comment by dieucao** [comment]
@jmprice Sounds good. I've prioritized the story in our backlog to remove the configuration.

**Comment by jmprice** [comment]
@dieucao Great, thank you very much!
