### ISSUE TITLE
Deleting user from an organization (via API directly) does not remove their org roles

### ISSUE THREAD

**Issue by kkamperschroer** [cloudfoundry/cf-release#659]
When using `cf curl` to hit the API directly, removing a user from the organization does not remove them from their corresponding roles in the org.

For example, I am an org manager and want to delete a second org manager. I could reasonably do so by running `cf curl -X DELETE /v2/organizations/32271cbf-c09f-4731-aabd-5740bad9145a/users/ac0ceda7-2b4e-4aa2-8ca8-ea880911c803` 

I no longer see them when running `cf curl /v2/organizations/32271cbf-c09f-4731-aabd-5740bad9145a/users`

I *still* see them when running `cf curl /v2/organizations/32271cbf-c09f-4731-aabd-5740bad9145a/managers` (*not expected*)

I *still* see them when running `cf org-users kyle` (*not expected*)

What's really interesting is that that second org manager no longer shows up when viewing them via PWS. It only shows one org member (myself) and does not show the other.

The deleted org manager can still `cf login` to the org and mess around with some things, such as revoking org manager permissions of other users, viewing app logs, etc.

**Comment by zaksoup** [comment]
Hi @kkamperschroer,

Thanks for submitting this issue! This is actually a bit of a confusing distinction for how users exist in the Cloud Controller. Essentially "user" is just another role on the CC. This is necessary because members of spaces must also be members of the org to which that space belongs, but not necessarily a privileged member.

What you're seeing is the expected behavior when deleting a user. You've deleted that "user" from the CC however the "user" as far as UAA is concerned is still a part of the "org managers" group (This is why you don't see them when listing users but do see them when listing manager). If you want to completely remove a user from an org you must individually remove them from each of the possible org roles. In your case since you specifically want to remove an org manager you should use the `v2/organizations/:guid/managers/:guid` endpoint.

Please let me know if you need further clarification!

Best,
Zak
CF Runtime Team.

**Comment by kkamperschroer** [comment]
It's slightly inconsistent with how it behaves if that user has any space roles. The API will return the following if the user still has any space roles:

```
{
   "code": 10006,
   "description": "Please delete the user associations for your spaces in the org.",
   "error_code": "CF-AssociationNotEmpty"
}
```

I figured that it would deal with org roles the same way. Essentially, I don't believe it should allow the deletion of the user until all of their org roles are removed.

Thanks for looking into it.

**Comment by zaksoup** [comment]
I think the problem is that the endpoint name and corresponding documentation is misleading. You're not deleting a user from the organization; you're removing the "user" role for what is technically a UAA user from an organization. In order for (UAA) users to have a role on a space they must also have a corresponding user role in that space's organization. Thus, removing the user's role from the organization throws the error your cite above.

**Comment by kkamperschroer** [comment]
Ok, I understand what you are saying. Thanks for your response.
