### ISSUE TITLE
Incompatibility with Diego

### ISSUE THREAD

**Issue by ldmberman** [cloudfoundry/cf-release#665]
There is a broken contract between the version of `tps` used in the current master of `diego-release` and the version of `cloud_controller_ng` used in `cf-release`: [the url](https://github.com/cloudfoundry/cloud_controller_ng/blob/e4e5294f1767257e294115da2a3c659f19a0ab94/lib/cloud_controller/diego/tps_client.rb#L17) that `tps` listens on was [changed](https://github.com/cloudfoundry-incubator/tps/commit/687b6231eb1526fb82d72cfc7b856e734a4adc3e). Therefore `cloud_controller_ng` should probably be updated at least to the state after [this commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/2f97ff7928f545a3bb7a29793e9b72eccef559bc) for `cf-release` to be compatible with `Diego`.

**Comment by ematpl** [comment]
Hi, @ldmberman,

The latest final version of cf-release is v207, which according to the [release notes](https://github.com/cloudfoundry/cf-release/releases/tag/v207) is compatible with diego-release 0.1099.0. Due to the experimental nature of Diego, we do not presently make guarantees of backwards compatibility even between final CF releases, and we create final releases from our testing pipeline much more frequently. As a result, it may be the case that the latest final release of Diego is not compatible with the latest final release of CF. The Diego team just started publishing a [comprehensive set of compatibility results](https://github.com/cloudfoundry-incubator/diego-cf-compatibility/blob/master/compatibility.csv) from our testing pipeline, though, so if you would like to find compatibilities between particular commit SHAs of CF and final releases or commit SHAs of Diego, that is currently your best resource.

Thanks,
Eric, for the CF Runtime Diego team

**Comment by ldmberman** [comment]
Thank you for clarification
