### ISSUE TITLE
Can't assign space role as OrgManager and SpaceManager

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/cf-release#693]
I have a user with role OrgManager and SpaceManager but I'm unable to assign a user as SpaceDeveloper. It looks like OrgManager is missing the `scim.read` permission. Where are permissions set for OrgManager/SpaceManager? Thoughts?

**Comment by dieucao** [comment]
Currently only admins are able to assign roles because of the permissions required to lookup usernames in UAA.
You could assign your user the additional admin related scims with uaac.

In the next month or two we'll be working on stories that should resolve this problem so that Org Managers and Space Managers can assign roles to other users without giving those users additional scopes.

As an OrgManager/SpaceManager, I can set org roles and space roles via username
https://www.pivotaltracker.com/story/show/88838792

As an admin, if I set org roles for a user that does not exist in Cloud Controller, the CC will automatically create a /v2/user, if external auth is configured
https://www.pivotaltracker.com/story/show/90565766

**Comment by longnguyen11288** [comment]
Thanks for info!
