### ISSUE TITLE
Does loggregator still use 4443?

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/cf-release#694]
I'm looking at `~/.cf/config.json` and loggregator is pointing at 443. Is 4443 needed anymore? Can we get rid of https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/templates/haproxy.conf.erb#L56-L66 and tcp backend?

**Comment by longnguyen11288** [comment]
It looks like templates are using 4443 https://github.com/cloudfoundry/cf-release/blob/6003f780fffc7e2e4dcf9ba76dc20a7bde65583c/templates/cf-infrastructure-aws.yml#L21-L22 but default is 443 https://github.com/cloudfoundry/cf-release/blob/master/jobs/cloud_controller_ng/spec#L365-L367

**Comment by DanLavine** [comment]
Hi @longnguyen11288,

Unfortunately we cannot remove the tcp backend. AWS restricts the use of port 443 and so we override the defaults in the templates to match our instructions on setting up the bosh machine (like [here](https://github.com/cloudfoundry/cf-release/tree/master/example_manifests#update-the-microbosh-security-group-to-allow-cf-logs-to-work)).

Hope this helps,
@DanLavine && @Quintaminant, CF Runtime Team

**Comment by jpalermo** [comment]
Looking closer, it is actually unrelated to AWS, since if you are using an ELB, you probably aren't using ha_proxy.

The reason 4443 is still in the ha_proxy config is to support logging using older CLI clients. It is not used for current CLI versions, but we still support back to version 6.0.0 of the CLI.
