### ISSUE TITLE
SSH into Warden or app container

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/cf-release#724]
I have successfully deployed cf-release. I wonder how can I SSH into my warden container or app containers in this case? I tried to access my `runner_z1` to ssh from there but I can't seem to do so.

Please advise

**Comment by drnic** [comment]
Perhaps look into the "cf console" CLI plugin - it lets users spin up a new container for an app that allows an ssh session into it via a proxy.

**Comment by kennetham** [comment]
@drnic yup I tried cf console. But nothing came up.

**Comment by kennetham** [comment]
@drnic I read 1 of your articles mentioning `bosh ssh` what is the remote host password I am expected to key in. I tried with `bosh ssh --public_key` but the connection timed out.

**Comment by utako** [comment]
hi @kennetham,

If you are referring to the "Enter password (use it to sudo on remote host)," that is a request for a password that will be used by bosh when creating a temporary user account. You can enter any password; it will only be relevant during that single SSH session and is used to, for example, `sudo`.

**Comment by kennetham** [comment]
@utako That is weird, I entered any password, but failed to establish a connection. In any case, are there alternatives which I can SSH in the applications in Warden? Can I control some of Warden specifics such as the port and IP address?

**Comment by kennetham** [comment]
I don't understand why I am always getting this SSH PublicKey issue. I generated the keypair from OpenStack, deployed CloudFoundry with this keypair, now when I try to `bosh ssh`

```log
Starting interactive shell on job runner_z1/0
Ubuntu 14.04.2 LTS
Permission denied (publickey).
```

Earlier when I tried to deploy CloudFounry, i had the same issue with this Keypair denying permissions. Why is this so?

**Comment by ematpl** [comment]
Hi, @kennetham,

The current version of Cloud Foundry does not directly support SSH connections directly to containers, although the still-experimental Diego container backend will. The `cf console` command referred to above is not part of the core CF CLI, but it is provided by the Console CF CLI plugin. To install that with a recent version of the CF CLI (6.10.0 or later), run

```
cf add-plugin-repo CF-Community http://plugins.cloudfoundry.org/
cf install-plugin Console -r CF-Community
```

It really sounds like you want some sort of interactive access into your app container, and SSH is but one means of doing so. Since you're in control of your bosh-deployed CF, you can `bosh ssh` onto the DEA running your container, and then use the warden shell client to get an interactive shell session into your container.

Once you're on the runner VM, change into the `/var/vcap/data/warden/depot` directory. There should be subdirectories under that with random looking names. Each one of these directories corresponds to a particular warden container running on that host; the names are their warden container handles. Change into one of those directories, and then run `bin/wsh`. This will give you an interactive session inside that warden container, and you can inspect it from there.

Best,
Eric

**Comment by kennetham** [comment]
Hi @ematpl,
I have installed the plugin console as suggested by @drnic, but where and how do I access that? `cf console` doesn't open anything. Also, I highlighted above, if you are aware, I do not understand why do I get a permission denied with the exact same `bosh.pem` key deployed to my VM.

Please advise. I have access the last method you mentioned, that worked, I am looking for alternatives possible.

Thank you.

**Comment by ematpl** [comment]
Hi, @kennetham,

Glad to hear you've been able to access warden containers via `bin/wsh`. I've never used the console plugin before myself, but its [GitHub repo](https://github.com/danhigham/cf-console) says you should be able to run `cf console <app-name>` for it to work.

I'm not sure why you're getting those errors when trying to `bosh ssh` into BOSH-deployed VMs on your OpenStack environment. Sounds like a BOSH issue rather than anything particular to cf-release, so you might raise an issue on the [BOSH repo](https://github.com/cloudfoundry/bosh) or the cf-bosh mailing list, if you haven't done so already.

Best,
Eric

**Comment by kennetham** [comment]
Hi @ematpl,
I am not sure if you are aware of this error, kind of need some advice on what's going on.

While deploying my CF app, it's failing to connect to the router at port 4443. I couldn't find any relevant documents or help online.

```log
Error dialing loggregator server: dial tcp 10.xxx.217.xx:4443: connection refused.
```

Right after that, my deployment failed. I had to run a few times before it worked, yesterday somehow my instance stopped running, I tried to redeploy but it keeps showing me an error.

Please advise.

As to the SSH, I will try that. I am wondering if I can pipe my commands in one string to directly get the handle ID, SSH into VM, then SSH using `bin/wsh`, or a script to do that?

**Comment by mheath** [comment]
The logger_endpoint.port property in your BOSH deployment manifest
determines what port is used to open a web socket to the Loggregator
backend to read your application's logs. So, you either need to configure
your front-end load balancer to use port 4443 or you need to change the
port to 443. Or you can turn off TLS all together by setting
logger_endpoint.use_ssl to 'false' and change logger_endpoint.port to 80.

-Mike

**Comment by Amit-PivotalLabs** [comment]
Hi @kennetham, it sounds like you've managed to access your containers via a warden shell (`bin/wsh`), great!  I will close out this issue, and if you continue to have other issues with BOSH or CF, feel free to open a new one.

Cheers,
Amit, CF OSS Release Integration PM
