### ISSUE TITLE
Failed to stage applications

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/cf-release#726]
Hi, I tried deploying cloudfoundry sample application `spring-music` and I keep getting this error.

It only succeeded once and I couldn't successfully deploy ever since.

```logs
FAILED
StagingError

TIP: use 'cf logs spring-music --recent' for more information
FAILED
StagingError

TIP: use 'cf logs spring-music --recent' for more information
[root@320 spring-music]# cf logs spring-music --recent
Connected, dumping recent logs for app spring-music in org hitachiyrl / space testgradle-02 as admin...

FAILED
Error dialing loggregator server: Get https://loggregator.cloudfoundry.yrl.intra.hitachi.co.jp:4443/recent?app=350acd65-b1f4-4fa7-8c50-47919aabce1d: dial tcp 10.xxx.217.xxx:4443: connection refused.
Please ask your Cloud Foundry Operator to check the platform configuration (loggregator endpoint is wss://loggregator.cloudfoundry.yrl.intra.hitachi.co.jp:4443).
```

Please advise.

**Comment by zaksoup** [comment]
Hi @kennetham 

I'm not sure why spring-music is failing to start but you're getting the error tailing logs because it appears that you've mis-configured your loggregator (doppler) job. 

Can you please give us:

your redacted bosh manifest for this deployment
the cf-push command you used to push spring-music
any other relevant information that might help us troubleshoot (infrastructure, custom configuration info, etc)

Thank you,
@zaksoup + @duncwinn, CF Release Integration (previously known as CF Runtime) team.

**Comment by zaksoup** [comment]
@kennetham I'm going to close this due to inactivity. If you're still having issues please comment and reopen.

**Comment by kennetham** [comment]
@zaksoup sure. Thanks, I will reopen if the issue persists.
