### ISSUE TITLE
Documentation missing port 4443 for loggregator in cf-public (Openstack)

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cf-release#746]
Hi,
I am not sure about this, but the documentation does not contain port 4443 which is need for loggregator communication in: http://docs.cloudfoundry.org/deploying/common/security_groups.html

Is this intended?

**Comment by Amit-PivotalLabs** [comment]
@elenasharma @kimahoff Do you know if this documentation issue is intentional?

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824302](https://www.pivotaltracker.com/story/show/99824302) Documentation missing port 4443 for loggregator in cf-public (Openstack)


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by kimahoff** [comment]
@Amit-PivotalLabs I seriously doubt it, though none of us can remember for certain. I added a story to the docs tracker to update. My guess would be that even if there was originally some reason for the omission, it must no longer be relevant.

**Comment by animatedmax** [comment]
I've added port 4443 to the cf-public security group in the Security Groups for Cloud Foundry document: http://docs.cloudfoundry.org/deploying/common/security_groups.html 

Thanks @jhiemer and @Amit-PivotalLabs

**Comment by dieucao** [comment]
@Amit-PivotalLabs The port that loggregator communicates on is configurable.  Some environments use 4443 because ELB's on AWS do not support http and websocket traffic over the same port.  Some environments have load balancers that does have support for both protocols on the same 443 port.

**Comment by jim80net** [comment]
In PWS, loggregator on port 4443 arose because AWS ELB's using the HTTP(s)
handler (which we want for providing things like X-Forwarded-For headers),
would not properly negotiate websockets. Therefore, loggregator traffic was
sent to port 4443, where the ELB was configured for simple TCP forwarding.

There is work being done on sending loggregator traffic to its own
ELB configured with the TCP handler on port 443 (bypassing the websocket +
HTTP problem). Provided this works as anticipated, this should be the
recommended configuration for future AWS deployments as well.

Thanks,


Jim
