### ISSUE TITLE
REST API Filtering Wildcard Issue

### ISSUE THREAD

**Issue by kevinroisin** [cloudfoundry/cf-release#760]
I'm having trouble using the wildcard `*` in the `q` query parameter in the v2 CloudFoundry REST API (documented here http://cloudfoundryjp.github.io/docs/reference/cc-api.html).

According to the docs (available at the link above), the following GET request should return all apps whose name begins with "some": `/v2/foo_bars?q=name:some*`

Doc except:
> Searching and Filtering are peformed via the q query parameter. The value of the q parameter is a key value pair containing the resource attribute name and the query value, e.g: GET /v2/foo_bars?q=name:some* would return both records shown in the pagination example above.

However, I’ve had no success in getting results using this. Example: while having an app named "Kevin-Test", sending a GET of `/apps?q=name:Kevin-Test` returns the expected details of my app named `Kevin-Test`, but a GET of `/apps?q=name:Kevin*` does not return any results (when I would expect at a minimum the same `Kevin-Test` app in the result list).

**Comment by Amit-PivotalLabs** [comment]
Hi @kevinroisin,

Let me ping some folks on the API team who manage [cloud controller](https://github.com/cloudfoundry/cloud_controller_ng).

/cc @zrob @dieucao 

Thanks,
Amit

**Comment by sykesm** [comment]
It was never implemented or supported.

A [TODO][1] was in the initial commit of query.rb and it was removed in a [purge][2] of TODO comments. 

[1]: https://github.com/cloudfoundry/cloud_controller_ng/blob/1e76821a9cb7742933acd9ef4ff3bb14c1d3725f/lib/vcap/rest_api/query.rb#L9
[2]: https://github.com/cloudfoundry/cloud_controller_ng/commit/5f8713259b3326939a657d3dfa66fbe79f2372d9#diff-73351e39f3b26bbc5a4186cb9f4fb3c5L13

**Comment by kevinroisin** [comment]
@sykesm thank you for your response. For what it's worth, this is a feature that would be useful for me and my team, as well as other teams I work with.

**Comment by Quintaminant** [comment]
Good afternoon @kevinroisin ,

As @sykesm said, it looks like this isn't currently a supported feature. As it turns out, we're presently trying to roll out a whole new API featureset (you can see the beginnings of this effort at the above link where things are marked "Experimental"). We're not currently expecting to include that feature as part of this change -- however, if you'd like to put this feature together, we do accept pull requests.

By the way, we noticed that the docs you linked to are not kept up-to-date anymore. We maintain the latest docs [here](http://apidocs.cloudfoundry.org/).

Health,
@Quintaminant & @jberkhahn, CF CAPI

**Comment by jeffpak93** [comment]
Hello! We're going to close this issue since it seems like there's nothing else to do at this point. Again, we do accept pull requests, so if there is interest in this feature please feel free to contribute! 

Thanks!
@jeffpak93 & @jberkhahn, CF CAPI
