### ISSUE TITLE
Documentation bug in the REST method: "/v2/resource_match"

### ISSUE THREAD

**Issue by jabrena** [cloudfoundry/cf-release#761]
Hi,

I am trying to develop a Node.js client and I was reading the documentation ( http://apidocs.cloudfoundry.org/214/resource_match/list_all_matching_resources.html ) to implement in the right way the method: "/v2/resource_match" but in my experimental tests, I didn't know the reason why this method returned a empty content:

```
http status: 200
[]
```

but documentation said that the method returns this JSON structure:

```
[{"sha1":"3722059cc37f7a56db064c1911f063da826cb211","size":36}]
```

Enabling traces for Go CLI:

```
set CF_TRACE=true
```

I was able to execute the method: cf push, and see the http requests and I noticed that the method returns a empty response:

```
Uploading StaticWebsiteHelloWorld...

REQUEST: [2015-08-06T14:11:31+02:00]
PUT /v2/resource_match HTTP/1.1
Host: api.MY_IP.xip.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.1-56792aa / windows

[{"fn":"index.html","sha1":"b657e91776782799aa20eee057603fe03ead4004","size":122},{"fn":"output.txt","sha1":"cc81d5428688235ff1e3cff139a5369d7a817a99","size":12479}]

RESPONSE: [2015-08-06T14:11:31+02:00]
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json;charset=utf-8
Date: Thu, 06 Aug 2015 12:10:03 GMT
Server: nginx
X-Cf-Requestid: 30904f59-005c-4ca1-48a3-2ed46996ba45
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 8acb0876-9116-473c-6d0a-9939167ada31::69998296-3130-46d6-9f16-ada90aaa309c

[]
```
Besides, it is necessary to update the documention about the JSON structure required for the parameter resources. Go cli sends to Cloud foundry this structure:

```
[{"fn":"index.html","sha1":"b657e91776782799aa20eee057603fe03ead4004","size":122},{"fn":"output.txt","sha1":"cc81d5428688235ff1e3cff139a5369d7a817a99","size":12479}]
```

but documentation says this one:

```
[{"sha1":"3722059cc37f7a56db064c1911f063da826cb211","size":36}]
```

Can you update the documentation to avoid more errors by the developers?

Juan Antonio

**Comment by sykesm** [comment]
@jabrena: The reference documentation appears to be correct. I think the issue is that you misunderstand the flow and purpose of the endpoint. Since the reference documentation doesn't include guidance on the use cases, you need to look in the code to see how it works.

When a client wants to upload artifacts to the cloud controller, it can first ask the cloud controller if it already has any of the artifacts cached locally or in its blob store. In order to do that, it sends the artifact size and hash to the cloud controller. The CC then looks in its store to see if the artifact exists and, if it does, it returns the json object the client provided in the response of *matched* resources.

The example does not have an `"fn"` key because it's not needed by the [code][1]. The CLI gets that information back because it sent it in the first place. In other words, is extra metadata that the CC preserves.

As to why you're getting an empty list back, that's simple. The CC simply hasn't cached any artifact that matches the hash and size you sent. The size range of artifacts that are stored are [configurable][2] and come from the [manifest][3] so you'll have to find out what the settings are on your target system.

[1]: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/resource_pool.rb#L98-L99
[2]: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/resource_pool.rb#L114-L116
[3]: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh-templates/cloud_controller_api.yml.erb#L195-L198

**Comment by Amit-PivotalLabs** [comment]
Hi @jabrena,

@sykesm has provided a detailed explanation (thanks!).  I've also responded to your question on the cf-dev mailing list titled *Doubt using the REST method: "/v2/resource_match"*, and opened an issue on the appropriate repo, namely [cloud controller](https://github.com/cloudfoundry/cloud_controller_ng/issues/410).

Best,
Amit

**Comment by jabrena** [comment]
Hi @Amit-PivotalLabs & @sykesm,

many thanks for the answer. I only read the API docs and I didn't understand the detail. I thought that I had some error.

@Amit-PivotalLabs, Today, I replied you, but I can't see the message:
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/FEK2WNLB5EMQ645TAZYYANL6P5AXMVFJ/

Does exist some delay to publish the messages in cf-dev?

Juan Antonio

**Comment by Amit-PivotalLabs** [comment]
Ah yes, the mailing lists were recently migrated, so things may have been lost if they were posted during the migration.  I'm not too sure about all that though.  Normally there should not be much of a delay.

**Comment by jabrena** [comment]
Oki.

Anyway, many thanks for the answer. I will try to use cf-dev! 
I go for last methods to upload an application! :)
http://apidocs.cloudfoundry.org/214/apps/uploads_the_bits_for_an_app.html

Juan Antonio
