### ISSUE TITLE
kill -9 in common/utils.sh:wait_pidfile doesn't always kill

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cf-release#762]
We have run across multiple cases where the kill -9 in the wait_pidfile() does not successfully kill -9 the running application.

```
[2015-07-18 00:19:18+0000] ------------ STARTING metron_agent_ctl at Sat Jul 18 00:19:18 UTC 2015 --------------
[2015-07-18 00:19:18+0000] ok: run: rsyslog: (pid 18153) 0s
[2015-08-06 22:19:24+0000] Killing /var/vcap/sys/run/metron_agent/metron_agent.pid: 18116
[2015-08-06 22:20:05+0000] ........................................
[2015-08-06 22:20:05+0000] Kill timed out, using kill -9 on 18116... Timed Out
```
```
root@b5b0ee0a-9b56-4139-be72-808eddb38ad1:/var/vcap/sys/log# ps -auxww|grep metr
vcap     18116  0.5  0.1 269524 10812 ?        D<   Jul18 157:48 /var/vcap/packages/metron_agent/metron --config /var/vcap/jobs/metron_agent/config/metron_agent.json
```

We have seen this also for cloud_controller as well.

When you hit this, BOSH/monit will still attempt to start a new instance and in most cases it will just flap until someone manually fixes it.

While this is stuck in a disk wait, we should retry a few times before giving up.  In bosh-lite there is little we can do, but in the real world, the disk wait may resolve itself.

**Comment by jpalermo** [comment]
From our investigation. The default monit timeout is 30 seconds, so the current behavior of doing a `kill` then waiting 25 seconds, then a `kill -9` if the process is still alive makes sense.

It sounds like doing multiple `kill -9` calls has no benefit, since the kernel is already handling the first one.

Increasing the monit timeout also has the potential to cause problems since BOSH does not wait for the `monit stop` call to complete and it will reload the monit config after ~90 seconds. When this happens, if the stop script is still running, and hasn't deleted the pid file, it is possible for monit to declare the old process as running, and BOSH will say it successfully updated the job, even though it is still running the old code (in a broken state).
