### ISSUE TITLE
Support for setting UAA log level

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-release#769]
I'd like to reduce UAA logging level to "INFO".  Any objection to a PR that sets sets all the "DEBUG" entries in this file:

https://github.com/cloudfoundry/cf-release/blob/develop/jobs/uaa/templates/log4j.properties.erb

To something configurable in a manifest defaulted to DEBUG?

**Comment by Amit-PivotalLabs** [comment]
@mbhave @sreetummidi what do you think?

**Comment by mbhave** [comment]
sounds good to me.

**Comment by sreetummidi** [comment]
Sounds good !


-Sree

**Comment by jpalermo** [comment]
#770

**Comment by Rohit04061992** [comment]
Hi Sree,
I am a big fan of yours, have seen all your roadmap videos and learned a lot,I am implementing Uaa in my project , all the configurations have been done now we are moving to production, scenario is we have hosted UAA as a appservice in Microsoft Azure  there we want to configure appinsights so that all the uaa logs are streamed to that manged service.For doing the same i need to use logback.xml at "uaa\uaa\src\main\resources"level, but tragedy is the internal projects are loading log4j.properties and my logbacl.xml is not getting loaded.

Could you please suggest what can i do so that i can overwrite logging strategy in Uaa.
