### ISSUE TITLE
[nfs_mounter] NFS server is always run without idmapd, still scripts are trying to use it

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/cf-release#827]
Hey, all.

Not long ago I got the following error on `nfs_z1/0` job: 
```
# tail -f /var/vcap/sys/log/rpc_nfsd_ctl.err.log
[2015-10-26 11:33:41+0000] dpkg: version 1:1.2.0-4ubuntu4.1 of nfs-kernel-server already installed, skipping
[2015-10-26 11:33:41+0000] /var/vcap/jobs/debian_nfs_server/bin/rpc_nfsd_ctl: line 31: /etc/init.d/idmapd: No such file or directory
```

This error is cased by [this line](https://github.com/cloudfoundry/cf-release/blob/5fd76c798be025101915912171ab80f85516968f/jobs/debian_nfs_server/templates/rpc_nfsd_ctl#L31). This script would fail if you add `set -x` option there. I checked deployed and working version of CF and found the same error in log files, in the same time there were no any notice of /etc/init.d/idmapd file in stemcell or release blobs.

Could you please check this should be fixed?

**Comment by Amit-PivotalLabs** [comment]
@dieucao do you mind taking a look?

**Comment by amitkgupta** [comment]
@dieucao @rmasand Any update on this issue?

**Comment by rmasand** [comment]
@amitkgupta @allomov it's my understanding that we're putting this issue and other NFS-related work on pause, until we spike on replacing NFS with WebDAV. [Tracker story](https://www.pivotaltracker.com/story/show/103941294v)

If we choose to stay with NFS, we will install the packages and dependencies on our bosh jobs explicitly (rather than expecting the stemcell to bring anything itself), as per [this tracker story](https://www.pivotaltracker.com/story/show/88810548). It's likely that installing nfs-common etc ourselves would clear up this missing daemon problem, or at least allow us to predict more accurately where it's located.

Seems like the team should get to this soon; I'll make a note in the story to update this issue when we know more.

**Comment by jeffpak93** [comment]
@Amit-PivotalLabs @allomov 

We just finished the spike on WebDAV and have decided on replacing NFS with WebDAV in a [new story](https://www.pivotaltracker.com/story/show/109604284). We'll give out another update when we've finished up work on this story.

**Comment by Amit-PivotalLabs** [comment]
I think the NFS -> WebDAV work is done, closing this issue.
