### ISSUE TITLE
Questions in deploying CF on AWS

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/cf-release#851]
Hello, all

I am trying to deploy CF on AWS based on http://docs.cloudfoundry.org/deploying/ec2/bootstrap-aws-vpc.html

My understand is that this deployment will launch several VM instance instead of the container in bosh-lite.

I had some questions regarding this document,

1. "Prepare a Domain"
Since we are deploying VMs in VPC, shouldn't the created zone to be VPC related? from the document it's "Public Hosted Zone"

2. bosh aws create
I had a try to run this and it failed because the limitation on elastic ip amount.
And I can see it trying to create all necessary resources used in CF deployment.
Would it be better to have a description about what kind of the resource will be created in this process?
So that I am aware of what resources are created and I can clean them up since "bosh aws destroy" cannot be used as it will erase all things. (or is there a command to do the clean up? )

3. bosh aws create
It creates databases we will use in customing the CF mannifest files. (uaa, uaadb?)

4. is the command "bosh aws create" be ran several times
I mean the 1st time when I run "bosh aws create", it will create some resources like VPC, subnet etc.
It may failed during this process and left some sources created.
If I run "bosh aws create" again, will it reuse these "created resources" again?

5. In the customization, we need to fill something about network etc.
If in "bosh aws create", we already created many subnets, shouldn't we just use them in the "Cloud Foundry Deployment Manifest Stub for AWS" sample?
It's quit strange to ask user "Replace the cf2 subnets: cloud_properties: static: 0.0.1.0 - 0.0.1.25 IP address range with a range of at least 26 consecutive IP addresses on your private network."

6. Is it must to create these uaa/uaadb externally?

I am new to touch CF v3, I had some experience in using CF v1.
But it's some totally different, especially in deployment.
And I found the document is not very clear for new guys to start with CF.
Thank you for help me to understand this.

**Comment by Amit-PivotalLabs** [comment]
Hi @StanleyShen 

1. The VPC makes it easy to control access to your VMs, so that most of them cannot be accessed directly by the outside world.  It also gives you a private IP space so that it's possible for BOSH to statically allocate IPs when necessary (e.g. when one VM needs to know the IP of another VM to reach it).  To actually use your Cloud Foundry when deployed within a VPC is usually accomplished by having a public-facing load balancer sitting in front, and all traffic goes through there.  The section on the domain is just configuring DNS so that you have a domain name that resolves to said load balancer.  You typically want that to be public so that you can push apps from your workstation, and the users of your apps can view those apps in their browsers at home, without having to get direct access behind the VPC firewall.

2. `bosh aws create` has not been actively maintained.  We are working on better tools to prepare your AWS environment, using CloudFormation.  In the mean time, yes, it is generally safe to `bosh aws destroy` if your `bosh aws create` fails, although it is a slow process.  I can't recall whether `bosh aws create` was sufficiently idempotent/re-entrant that you can just run it again until it succeeds.  How many elastic IPs do you currently have in your account?  I believe the default limit in EC2 is 5, which should be enough for this CF deployment, unless you're already using a bunch of elastic IPs already for other things.

3. Yes, it creates Amazon RDS databases for the UAADB and CCDB.

4. Briefly looking at the code, yes, it looks re-entrant.  It uses a "migration" system, so each step in the "aws create" is a migration, and next time you run it, it determines which migrations need to run and only runs those.

5. I have recently made changes to those docs, however the changes haven't made it to production yet.  In principle, that document should make sense for someone whether or not they used `bosh aws create` to get started.  Generally speaking, you need to include in that network section: the CIDRs of your subnets, the default DNS IP for your VPC, the "Gateway" for each of your subnets (the first .1 IP in each CIDR).  The "Reserved" IPs are IPs .2 - .9 for each CIDR.  You need to set aside some number of IPs within each subnet for BOSH to statically allocate to VMs.  It doesn't strictly have to be 25 consecutive IPs, but that will work.  So you can do x.x.x.10-x.x.x.35, fill in the x.x.x depending on your subnet's CIDR.

6. It is not a must to create UAADB and CCDB externally, no.  (To clarify, UAA and CC are Cloud Foundry components, they will always be internal.  Both use a postgres or mysql database, referred to as UAADB and CCDB, those can be internal or external).  The cf-release contains a postgres job, so you could use that instead of RDS.

**Comment by Amit-PivotalLabs** [comment]
Seems like you don't have any follow-up questions here @StanleyShen, closing.
