### ISSUE TITLE
failed to delete a service due to binding IP missing.

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/cf-release#863]
Hi experts,

I met a dead loop which is caused by a missing binding ID. 

The story is somehow(i don't really know how because I did nothing special before) one of my binding ID got lost, due to which I cannot delete the service or the bound app.

When I try to delete the APP or unbind the service with the app, it will complains about the missing binding ID

When I try to delete the service, it will complain that the service is bound to an app and the binding must be delete first.

Neither can I delete the space or the org.

- How can a binding ID get lost?
- How can I fix this?

**Comment by Amit-PivotalLabs** [comment]
Hey @yyl8815 

That's quite strange.  Can you share some output from `cf app` and `cf service`.

@dieucao @zrob @utako here's a weird issue with service bindings, any idea?

**Comment by dieucao** [comment]
@yyl8815 It would be helpful if you could provide what cc api version or cf-release you are using and if you could provide a trace of what happens when you attempt to delete the service, `CF_TRACE=trace.txt cf delete-service SERVICE_NAME -f`

Alternatively, if you are using at least cf-release 218 with cc api version 2.36, with the latest cf cli and you have access to an admin user you can purge the service instance from cloud controller's knowledge.

```
$ cf help purge-service-instance
NAME:
   purge-service-instance - Recursively remove a service instance and child objects from Cloud Foundry database without making requests to a service broker

USAGE:
   cf purge-service-instance SERVICE_INSTANCE

WARNING: This operation assumes that the service broker responsible for this service instance is no longer available or is not responding with a 200 or 410, and the service instance has been deleted, leaving orphan records in Cloud Foundry's database. All knowledge of the service instance will be removed from Cloud Foundry, including service bindings and service keys.

OPTIONS:
   -f       Force deletion without confirmation
```

**Comment by shalako** [comment]
Closing as we've receive no response
