### ISSUE TITLE
Access Applications hosted in Cloud Foundry VM from Host Network

### ISSUE THREAD

**Issue by faizi1407** [cloudfoundry/cf-release#907]
Hi All,

I am not so good at networking, I have a Host machine with a Cloud Foundry (Bosh-Lite) VM. I have successfully deployed an App in cloud foundry. After running route.bat in my host machine i am able to access the application from Host. But how do i make the application accessible from a particular network or lets say just the host machines' network.

Thanks,
Faizan :-)

**Comment by APShirley** [comment]
Hi @faizi1407,

We want to make sure we understand your question. 
 - When you refer to the network, do you mean the local network that the host machine is on?
 - When you refer to the host do you mean the machine running the vagrant vm? 
 - When you say make the application accessible do you mean the ability to `bosh ssh` and `cf push` from your host machine, or do you mean simply being able to make `http` requests to your own application endpoint?

 Thanks,
 - Al & @nimakaviani

**Comment by faizi1407** [comment]
Hi **Shirley**,

- Yes, when i said network i meant local network that host machine is one .
- yes host means the machine where i am running vagrant VM
- For the 3rd point i want all the possibilities, bosh ssh and cf push from any machine and application accessible from anywhere(internal n/w as well as external n/w i.e internet)

Scenario is Host machine **( 10.x.x.x)** 
Vagrant VM **( eth0 - 10.x.x.x, eth1 - 10.x.x.x)** Same ip range 
CF API endpoint by default its **(10.244.0.34 ),** all applications are hosted on this ip it seems. So how can i make this ip accessible from my local network and from the internet, or there is another workaround for this ??

Thanks,
**Faizan**

**Comment by APShirley** [comment]
Hi @faizi1407,

If you take a look at the `add-route.bat` file that is included with bosh-lite you can see that it really only sets up networking for the local machine:
```bat
@echo off
echo Adding the following route entry to your local route table to enable direct warden container access. You may have to run this in a command prompt with elevated administrator privileges.
echo   - route add 10.244.0.0/19 192.168.50.4
echo.
route add 10.244.0.0/19 192.168.50.4
```

bosh-lite is designed for local development and hacking on CF and other bosh releases. It was never intended to be used for publicly hosting apps. It sounds like what you're trying to do would require deploying your CF on a public IaaS like AWS. That way, you can easily set up a public IP, load balancing, real networking config, etc.

To get an idea for how to do this, take a look at the [CF docs for getting started](http://docs.cloudfoundry.org/deploying/aws/). You can follow the instructions there for deploying. To get a "minimal" deployment, you can use [this manifest](https://github.com/cloudfoundry/cf-release/blob/master/example_manifests/minimal-aws.yml) to deploy CF.

(As an aside, we think it is theoretically possible to set up your routing tables in such a way. We've never tried to make a bosh-lite accessible to the rest of our private network, much less publicly available on the internet. Also, we don't work on Windows machines so we'd be the wrong people to ask about Windows networking configuration.)

Since the original problem described in this issue (networking config on your machine) is out-of-scope for cf-release and bosh-lite, we're going to close this ticket. Feel free to open a new issue if you come across other problems deploying CF.

Al && @dsabeti 
CF Release Integration Team
