### ISSUE TITLE
./scripts/update fails - Failed to recurse into submodule path 'src/consul-release'

### ISSUE THREAD

**Issue by mawi200** [cloudfoundry/cf-release#916]
After checking out cf-release (release 231) running ./scripts/update fails with 

> Failed to recurse into submodule path 'src/consul-release'

No further error is shown. 
However, I do receive the same error message when running the bosh-lite/bin/provision_cf script.

**Comment by Infra-Red** [comment]
Try to checkout latest branch and then run next:
```
git submodule foreach --recursive 'git submodule sync'
git submodule update --recursive
```

**Comment by APShirley** [comment]
@Infra-Red yes that's correct; this already happens in `./scripts/update` - see https://github.com/cloudfoundry/cf-release/blob/master/scripts/update#L37-L38

@mawi200 we did the following:

```
git clone https://github.com/cloudfoundry/cf-release/
cd cf-release
git checkout v231
./scripts/update
```

and it was successful.

Can you provide exactly the steps you performed to observe this issue?

Thanks,
- Al && @robdimsdale

**Comment by mawi200** [comment]
Thank you for the comments.

The issue seems to be related to network settings. I am accessing github from behind a proxy (http and https). Cloning the git repository works without issue and also updating seems to work fine until the procedure tries to recurse into 'src/consul-release'.
I tried both options described above but they both result in error for me. 

However, I tested the same procedure in a setting where I am not behind a proxy and there the update worked just fine.

**Comment by APShirley** [comment]
@mawi200 

We think we found the problem. There's a submodule inside of `src/consul-release` that has a `git://` scheme instead of `https://`. It could be that this is where the script is failing to recurse when you're behind the proxy (how the proxy affects this, we're not sure).

Could you try something? 
- Run `git submodule update --init` in cf-release. This should get `src/consul-release`, but not any of it's submodules. 
- Then, `cd src/consul-release && git submodule update --init` -- we think this submodule update will fail. 
-  Then edit the last line of `consul-release/.gitmodules` and change the scheme from `git://` to `https://`:

```
url = git://github.com/pivotal-cf-experimental/destiny 
   => 
url = https://github.com/pivotal-cf-experimental/destiny
```
-  Finally re-run `git submodule update --init`, if the git scheme is the culprit this should now work.

In the meantime we will get in touch with the consul-release team and ask about this git scheme and if there is any reason why it is not `https`. @zankich, any thoughts?

- Al && @dsabeti

**Comment by valenbb** [comment]
I can confirm that trying to get src/consul-release is using ssh scheme rather than https when behind a proxy. Made a git config change on the bosh-init machine to use https:
git config --global url."https://".insteadOf git://

Reran the scripts/update and the issue stopped.

Also, in a test environment without proxy, scripts/update was successful.

**Comment by robdimsdale** [comment]
@mawi200 @valenbb The infrastructure team has fixed this in consul-release (v63). The change has yet to be propagated to a final version of cf-release, but this should be fixed once cf-release v232 gets cut.

Rob && @dsabeti

**Comment by APShirley** [comment]
Closing this issue as it has been resolved in latest release.

**Comment by suchakra012** [comment]
Hello,

I am facing with the issue of while doing cf deployment using bosh-lite director-
 Failed to recurse into submodule path 'src/consul-release'

I have checked out of cf release (v235) & run /bin/provision.cf script .

The snippet of error log is here -

Cloning into 'C:/Users/ECTYSAN/Documents/workspace/cf-release/src/loggregator/src/github.com/stretchr/testify'...
Cloning into 'C:/Users/ECTYSAN/Documents/workspace/cf-release/src/loggregator/src/github.com/tedsuo/ifrit'...
Cloning into 'C:/Users/ECTYSAN/Documents/workspace/cf-release/src/loggregator/src/github.com/ugorji/go'...
Submodule 'dropsonde-protocol' (https://github.com/cloudfoundry/dropsonde-protocol) registered for path 'src/loggregator/src/github.com/cloudfoundry/dropsonde/dropsonde-protocol'
Cloning into 'C:/Users/ECTYSAN/Documents/workspace/cf-release/src/loggregator/src/github.com/cloudfoundry/dropsonde/dropsonde-protocol'...
Submodule 'definitions' (https://github.com/cloudfoundry/dropsonde-protocol.git) registered for path 'src/loggregator/src/github.com/cloudfoundry/sonde-go/definitions'
Cloning into 'C:/Users/ECTYSAN/Documents/workspace/cf-release/src/loggregator/src/github.com/cloudfoundry/sonde-go/definitions'...
Submodule 'src/uaa' (https://github.com/cloudfoundry/uaa.git) registered for path 'src/uaa-release/src/uaa'
Cloning into 'C:/Users/ECTYSAN/Documents/workspace/cf-release/src/uaa-release/src/uaa'...
Failed to recurse into submodule path 'src/consul-release'
Failed to recurse into submodule path 'src/etcd-release'

their is no network proxy enable in my setup & I the url in .gitmodule file in src/consul-release is having this url -

[submodule "src/acceptance-tests/vendor/github.com/pivotal-cf-experimental/destiny"]
        path = src/acceptance-tests/vendor/github.com/pivotal-cf-experimental/destiny
        url = https://github.com/pivotal-cf-experimental/destiny

Can any one guide what to do here. I am stuck in the deployment process. It will be helpful if you can suggest which cf release to go using bosh-lite deployment.

Cheers !
Suman

@APShirley @Infra-Red

**Comment by ra1100** [comment]
@suchakra012 
Had the same issue.  This worked for me:
Edit the following file and apply the fix to the URL mentioned above (replace git:// with https://)

./src/consul-release/src/acceptance-tests/vendor/github.com/cloudfoundry-incubator/check-a-record/.gitmodules
