### ISSUE TITLE
the stack could not be found: The requested app stack cflinuxfs2 is not available on this system.

### ISSUE THREAD

**Issue by olzorenko** [cloudfoundry/cf-release#932]
Hello all,

Same here.

We've faced this problem:

the stack could not be found: The requested app stack cflinuxfs2 is not available on this system.

Also we've noticed that it's appearing from time to time. If we try to push an app again few more time (with 5-10 sek delay) - it's pushing normally. 

We're assuming this may be caused by simultaneous deployment. For instance - if I push app A and at the same time someone push app B - that someone will have such error. We think the reason of such behavior is stack under lock while deployment A in progress.

Are we right? Or please advise what shall we do to resolve this issue.

CF CLI VERSION: cf version 6.14.0+2654a47-2015-11-18
CF version: 225

Best Regards,
Oleksii.

**Comment by robdimsdale** [comment]
@olzorenko to our knowledge there is no global lock on the stack, and no reason why pushing two apps simultaneously should not work.

What infrastructure are you on? We assume you are using dea and not diego. Can you provide the logs for the `api_z1` and `runner_z1` jobs and your deployment manifest (both redacted)?

Thanks,
Rob & @nimakaviani

**Comment by olzorenko** [comment]
Hello @robdimsdale 

We're using vSphere as infrastructure with DEA (cf version 225).

Please find logs by this link (google drive) and manifest in attachment.

https://drive.google.com/folderview?id=0B7HcBh-H6d-7WldYRENYT0ZKbU0&usp=sharing
[cf-manifest_wiped.yml.zip](https://github.com/cloudfoundry/cf-release/files/175827/cf-manifest_wiped.yml.zip)

Best Regards,
Oleksii.

**Comment by olzorenko** [comment]
Just realized that I've posted all logs, not only the latest ones.

I've downloaded logs from api (0 and 1) and runner (0 and 1) in 1-2 minutes after mentioned error appears (so it should be in the end of the log files).

Best Regards,
Oleksii.

**Comment by APShirley** [comment]
@olzorenko,

We had a look at your manifest and there is an empty array of `stacks` under the `cc` job which we think is possibly causing your problem. Can you try deleting the line (:922) from your manifest and tell us if that fixes the issue.
```yaml
    stacks: 
```
 From the logs you posted, it seems that one of the two cloud controllers can not stage apps properly and the reason you see the failure is because your requests to deploy an app are load-balanced between the two cloud controllers you have deployed. Once the requests hit the good cloud controller, your deployment goes through without a problem, but when they hit the bad cloud controller, they fail with the error you see. Pushing apps simultaneously means one of the two pushers will probably hit the bad cloud controller.

Also, you may want to rotate your passwords as we noticed the logs you posted are not sanitized, and leaked at least one password (we think).

Thanks
Al & @nimakaviani

**Comment by APShirley** [comment]
Closing this issue as it hasn't had any activity for 8 days. If you need anymore help please feel free to open a new issue. 

Cheers,

Al
