### ISSUE TITLE
Can you add --local to only use local cache to install ruby 2.1.8 or 2.2.4?

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/cf-release#947]
Sometime the network to rubygems.org is not stable, especially in some countries. So when deploying cloud foundry, the tasks always fails in compiling ruby. 

Could you add --local to below two lines to only use local cache when compiling ruby?

[${BOSH_INSTALL_TARGET}/bin/gem install ruby-2.1.8/bundler-${BUNDLER_VERSION}.gem --no-ri --no-rdoc](
https://github.com/cloudfoundry/cf-release/blob/d58979fa9d54eeeebe71beca527e7745c4db237a/packages/ruby-2.1.8/packaging#L32)

[${BOSH_INSTALL_TARGET}/bin/gem install ruby-2.2.4/bundler-${BUNDLER_VERSION}.gem --no-ri --no-rdoc](https://github.com/cloudfoundry/cf-release/blob/d58979fa9d54eeeebe71beca527e7745c4db237a/packages/ruby-2.2.4/packaging#L31)

**Comment by APShirley** [comment]
Hi @AbelHu,
It seems like the --local option expects the gems it installs to be present locally, which will not be true on the compilation VM because they are not vendored in as dependencies of the ruby package. You could modify your local copy of cf-release and build a release to test your suggestion out - if it works we would be happy to accept a Pull Request.

If your suggestion doesn't work, you could address your actual concern of inability to compile ruby during a deploy by trying pre-compiled packages - https://bosh.io/docs/packages.html may be helpful.

Let us know if you have further questions or would like to submit a Pull Request.

Thanks,
Al & @robdimsdale

**Comment by robdimsdale** [comment]
@AbelHu as it's been a week without response we will close this issue. Please feel free to open another issue or a PR.

Thanks,
Rob
CF Release Integration
Pivotal
