### ISSUE TITLE
Consul_z1/0 is not running after update

### ISSUE THREAD

**Issue by valenbb** [cloudfoundry/cf-release#949]
IAAS: vsphere-cpi
BOSH: latest version in centos 7
cf-release: latest version
stemcell: latest ubuntu
bosh dorector: latest ubuntu stemcell

Observing error below after fixing IP conflicts:

==============================================
  Started updating job consul_z1
  Started updating job consul_z1 > consul_z1/0 (4a91d405-8175-4535-b07b-5d3d18e42a5c) (canary). Failed: `consul_z1/0 (4a91d405-8175-4535-b07b-5d3d18e42a5c)' is not running after update. Review logs for failed jobs: consul_agent (00:11:28)

Error 400007: `consul_z1/0 (4a91d405-8175-4535-b07b-5d3d18e42a5c)' is not running after update. Review logs for failed jobs: consul_agent

Task 26 error

For a more detailed error report, run: bosh task 26 --debug

===============================================

I ssh into consul_z1 and found the following:

error during start: rpc error: failed to get conn: x509: certificate is valid for *.cfvmware.research.ge.com, not server.dc1.cf.internal
2016/04/13 14:06:22 [ERR] agent.client: Failed to decode response header: EOF
2016/04/13 14:06:22 [ERR] agent.client: Failed to decode response header: EOF 

Certs were generated using certstrap as specified in the document.
Not sure what cf.internal is used for, other than internal routing.

Checked certs in jobs folder and they match what is specified in stub file.

I am not sure where else to look. 
Any advice and assistance is appreciated.

Thanks!

**Comment by gdean123** [comment]
Hi valenbb,

It looks like you are using a certificate that has been generated with a common name of *.cfvmware.research.ge.com, but you didn't update the manifest properties to reference the new domain. If you update properties.consul.agent.domain to be cfvmware.research.ge.com in the cf manifest, you should be good to go.

Alternatively, you could use [this script](https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-consul-certs#L18) to generate certificates with common name server.dc1.cf.internal.

Thanks!
George and @christianang

**Comment by valenbb** [comment]
Thanks George and @christianang. 

I decided to leave cf.internal intact in the manifest and generate certs specific to the server. This worked successfully. 

Last week, I did figure out changing cf.internal to match my domain and that worked until another error appeared, so I decided to retry from a clean slate this week. Then i stumbled into the same error when using my domain:

error during start: rpc error: failed to get conn: x509: certificate is valid for *.cfvmware.research.ge.com, not server.dc1.cfvmware.research.ge.com
2016/04/13 14:06:22 [ERR] agent.client: Failed to decode response header: EOF
2016/04/13 14:06:22 [ERR] agent.client: Failed to decode response header: EOF

Just curious why this is not documented for vsphere? I do apologize if I missed it somewhere.

**Comment by gdean123** [comment]
Hi valenbb,

We wanted to better understand your use case for changing the domain from server.dc1.cf.internal to cfvmware.research.ge.com, since this domain is only used for internal service discovery within Cloud Foundry. Is there something special about your installation that makes it desirable to customize the domain?

We are guessing that part of the confusion here is that the server.dc1.cf.internal domain is hardcoded in scripts/generate-consul-certs and is not mentioned in the docs. Would this situation have been clearer if that script took the domain as a parameter and was mentioned on [this page](https://docs.cloudfoundry.org/deploying/common/consul-security.html)?

Thanks!
George and @zankich

**Comment by valenbb** [comment]
Hi George and @zankich,

You have hit the reason excellently:

"We are guessing that part of the confusion here is that the server.dc1.cf.internal domain is hardcoded in scripts/generate-consul-certs and is not mentioned in the docs."

I was thinking that domains would be our chosen domain. If mentioned in the docs, that this is hardcoded for internal working in CF, users like myself would not have to generate consul certs.

I think the suggestion to take the domain as a parameter and mentioned would make things much better. Or, could this section be automated so we don't have to touch it during cf-stub creation?

What I find interesting is that my colleague uses the openstack-cpi and never encountered this situation. It is possible that his version of CF is from back in February of 2016 and each cpi work differently.

Just would like you to know that I am enjoying the learning process and am not upset. This is great work, and if I can bring things light, I am happy.

**Comment by gdean123** [comment]
Hi valenbb,

Thanks so much for the feedback. We have captured this plan in this upcoming story:

https://www.pivotaltracker.com/story/show/117638983

We believe that your colleague using the openstack-cpi did not run into this problem because older versions of consul-release had cf.internal hardcoded as it's internal domain.

Thanks,
George and @zankich
