### ISSUE TITLE
statsd_injector fails to start due to missing package

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/cf-release#950]
```
   Failed updating job api_z2 > api_z2/0 (ce3ef9ef-c9a2-40fe-b262-49964fb08514): `api_z2/0 (ce3ef9ef-c9a2-40fe-b262-49964fb08514)' is not running after update. Review logs for failed jobs: statsd-injector (00:13:48)
```

cf-release points to this version of statsd-injector in loggregator:
 https://github.com/cloudfoundry/loggregator/tree/c57eaa5f3f6330e10e3b3bc209b195a85635fedf/jobs/statsd-injector

statsd-injector can't start because it can't find file `/var/vcap/packages/common/utils.sh`.

https://github.com/cloudfoundry/loggregator/blob/c57eaa5f3f6330e10e3b3bc209b195a85635fedf/jobs/statsd-injector/templates/statsd-injector-ctl.erb#L7

This is provided by the `common` package but statsd-injector doesn't list it as a dependency. We used to have the `route_registrar` job installed alongside and it would provide the `common` package. But we don't use `route_registrar` anymore.
 
This is fixed in loggregator master: https://github.com/cloudfoundry/loggregator/blob/master/jobs/statsd-injector/templates/statsd-injector-ctl.erb#L10-L11

Upgrading loggregator in cf-release should fix the issue.

**Comment by dsabeti** [comment]
Hey @saliceti. Thanks for pointing this out. It looks like loggregator was [bumped in the develop branch of cf-release](https://github.com/cloudfoundry/cf-release/commit/6be73210433e4282496522117e8f11970f156f3e), so these changes will be included in the next final release of cf.

If you're experimenting or working with a non-production deployment, you could try to use the `release-candidate` branch, but we can't make any guarantees about it's performance/stability just yet. Otherwise, you'll have to wait for the next final release to be cut -- which typically happens every week or two.

David && @robdimsdale 
CF Release Integration Team
