### ISSUE TITLE
233 release notes & libmysqlclient warning

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/cf-release#964]
The 233 release notes stacks section mentions "cflinuxfs2 has dropped support for libmysqlclient in favor of libmariadbd". This section should include a warning (or better yet, an item in the bulleted important section at the top) detailing the repercussions of the change and the required workaround for this version: the buildpack cache needs to be deleted and the app has to be restaged.

See list thread here for additional details: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/CHRX7S5WVQZKIEJW5AQIDBNDBKC2V4O4/

**Comment by jvshahid** [comment]
Afaik this isn't necessary. libmysqlclient.so files were  reintroduced to avoid restaging the applications or removing the cache. Old applications that link to libmysqlclient.so should continue to work. That said, new applications should be fine as long as they use mysql_config which is the case for rails and other frequently used libraries. /cc @flavorjones for more context. Apologies for any typos since I'm typing this on my phone

**Comment by cholick** [comment]
@jvshahid Right, but they were reintroduced in 234. I'm just suggesting adding a warning to the 233 release page since it's where the break happened. Anyone deploying 233 would have to look ahead to 234 and notice the issue.

**Comment by Dannyzen** [comment]
Thanks Matt. We'll take a look early next week. We appreciate you bringing
this to our attention.

**Comment by flavorjones** [comment]
Agree, let's just make a short update to v233 release notes at https://github.com/cloudfoundry/cf-release/releases/tag/v233 to clarify, please.

**Comment by Dannyzen** [comment]
I've added the following changes to the [release notes](https://github.com/cloudfoundry/cf-release/releases/tag/v233).
* v233 includes a [change in cflinuxfs2](https://github.com/cloudfoundry/stacks/releases/tag/1.45.0) that removes support for libmysqlclient in favor of libmariadb. This will require a clearing of buildpack cache and a restaging of apps for the changes to take place.

+1 for closure?
