### ISSUE TITLE
Error 400007: 'api_z1/0  is not running after update.

### ISSUE THREAD

**Issue by frantisek121** [cloudfoundry/cf-release#985]
Hello,

I am trying to deploy CF on OpenStack kilo. I tried:

* bosh stemcell 3232.4, then I tried 3147 (because I have found that this version was working for someone with similar problem)
* bosh 256.2
* bosh-openstack-cpi 24

I am getting:

```
 Started updating job api_z1 > api_z1/0 (8cdfa191-dd27-4759-9c6a-8c80efd4f240) (canary). Failed: 'api_z1/0 (8cdfa191-dd27-4759-9c6a-8c80efd4f240)' is not running after update. Review logs for failed jobs: cloud_controller_ng, cloud_controller_worker_local_1, cloud_controller_worker_local_2, nginx_cc, cloud_controller_worker_1 (00:11:00)
Error 400007: 'api_z1/0 (8cdfa191-dd27-4759-9c6a-8c80efd4f240)' is not running after update. Review logs for failed jobs: cloud_controller_ng, cloud_controller_worker_local_1, cloud_controller_worker_local_2, nginx_cc, cloud_controller_worker_1
```

I have DNS server in my project, but it seems to me it works fine.

On failing api server:

```
root@fde841a6-9ec5-4166-a076-25b6cdfd9d7e:~# ping somethingblabla.domain.com
PING somethingblabla.domain.com (10.251.207.205) 56(84) bytes of data.

10.251.207.205 - FIP for HA.

root@fde841a6-9ec5-4166-a076-25b6cdfd9d7e:~# monit summary
The Monit daemon 5.2.4 uptime: 12m

Process 'cloud_controller_ng'       not monitored
Process 'cloud_controller_worker_local_1' not monitored
Process 'cloud_controller_worker_local_2' not monitored
Process 'nginx_cc'                  not monitored
Process 'cloud_controller_migration' running
Process 'cloud_controller_clock'    running
Process 'cloud_controller_worker_1' Does not exist
Process 'metron_agent'              running
Process 'statsd-injector'           running
Process 'route_registrar'           running
System 'system_fde841a6-9ec5-4166-a076-25b6cdfd9d7e' running
```

I did check logs `/var/vcap/sys/log/cloud_controller_ng/`. `cloud_controller_ng_ctl.err.log` has a lot of lines like this:

```
 ------------ STARTING cloud_controller_ng_ctl at Tue Jun 21 08:28:42 UTC 2016 --------------

cloud_controller_ng_ctl.log:
------------ STARTING cloud_controller_ng_ctl at Tue Jun 21 08:29:29 UTC 2016 --------------
[2016-06-21 08:29:29+0000] Checking for blobstore availability
[2016-06-21 08:29:59+0000] Blobstore is not available
```

pre-start.stderr.log:

```
++ dirname /var/vcap/jobs/cloud_controller_ng/bin/pre-start
+ SCRIPT_DIR=/var/vcap/jobs/cloud_controller_ng/bin
+ source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh
++ export PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ app_domains=app.domain.com
+ system_domain=sys.domain.com
+ ruby /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb sys.domain.com app.domain.com
+ exit 0
++ dirname /var/vcap/jobs/cloud_controller_ng/bin/pre-start
+ SCRIPT_DIR=/var/vcap/jobs/cloud_controller_ng/bin
+ source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh
++ export PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ app_domains=app.domain.com
+ system_domain=sys.domain.com
+ ruby /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb sys.domain.com app.domain.com
+ exit 0
```

There is "+ ruby /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb sys.domain.com " - that makes me worried about my DNS settings, but still wild card *domain.com gets resolved on all nodes.

I have noticed log "Blobstore is not available" so I checked  blobstore_z1/0:

```
root@a5768e2b-87fd-4302-9c6d-3029fdfb98ca:~# monit summary
The Monit daemon 5.2.4 uptime: 17h 13m

Process 'consul_agent'              running
Process 'metron_agent'              running
Process 'blobstore_nginx'           running
Process 'blobstore_url_signer'      running
Process 'route_registrar'           running
System 'system_a5768e2b-87fd-4302-9c6d-3029fdfb98ca' running

root@a5768e2b-87fd-4302-9c6d-3029fdfb98ca:~# ping bla.domain.com
PING bla.domain.com (10.251.207.205) 56(84) bytes of data.
```

I have recently posted a question to mail list to verify stub.yml file (not answered) - I found documentation on this subject a little unclear, perhaps because it should be obvious to most people. Just to check - is it ok to use certs generated by generate-consul-certs like this? In config file I would replace content of brackets with content of the files. Just for - CONSUL_ENCRYPT_KEY ('') I am using ''" as empty string:

```
hm9000:
    server_key: HM9000_SERVER_KEY (hm9000_server.key)
    server_cert: HM9000_SERVER_CERT (hm9000_server.crt)
    client_key: HM9000_CLIENT_KEY (hm9000_client.key)
    client_cert: HM9000_CLIENT_CERT (hm9000_client.crt)
    ca_cert: HM9000_CA_CERT (hm9000_ca.crt)

consul:
    encrypt_keys:
      - CONSUL_ENCRYPT_KEY ('') 
    ca_cert: CONSUL_CA_CERT (server-ca.crt)
    server_cert: CONSUL_SERVER_CERT (server.crt)
    server_key: CONSUL_SERVER_KEY (server.key)
    agent_cert: CONSUL_AGENT_CERT (agent.crt)
    agent_key: CONSUL_AGENT_KEY (agent.key)

tls:
      port: 443
      cert: BLOBSTORE_TLS_CERT (server.crt)
      private_key: BLOBSTORE_PRIVATE_KEY (server.key)
      ca_cert: BLOBSTORE_CA_CERT (server-ca.crt)
```

Some more info:

```
[root@cloudfoundry ~]# bosh instances --vitals
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on deployment 'openstack-prod' on 'my-bosh'

Director task 12

Task 12 done

+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| Instance                                                                   | State   | AZ  | VM Type   | IPs            |         Load          |       CPU %       | Memory Usage | Swap Usage | System     | Ephemeral  | Persistent |
|                                                                            |         |     |           |                | (avg01, avg05, avg15) | (User, Sys, Wait) |              |            | Disk Usage | Disk Usage | Disk Usage |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| api_z1/0 (8cdfa191-dd27-4759-9c6a-8c80efd4f240)*                           | failing | n/a | large_z1  | 192.168.0.104  | 0.04, 0.06, 0.05      | 0.3%, 0.4%, 0.0%  | 4% (300.7M)  | 0% (0B)    | 46%        | 2%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| blobstore_z1/0 (13444782-9086-471f-b5ab-4fc417ed227a)*                     | running | n/a | medium_z1 | 192.168.0.102  | 0.00, 0.01, 0.05      | 0.1%, 0.2%, 0.1%  | 3% (106.7M)  | 0% (0B)    | 46%        | 1%         | 0%         |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| consul_z1/0 (db7148d9-d5a0-41a1-9fc9-ac74712ace16)*                        | running | n/a | small_z1  | 192.168.0.137  | 0.00, 0.01, 0.05      | 0.3%, 0.2%, 0.3%  | 4% (81.8M)   | 0% (0B)    | 46%        | 1%         | 0%         |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| doppler_z1/0 (b1956f94-031e-4b25-abbc-4111ae9a6543)*                       | running | n/a | medium_z1 | 192.168.0.107  | 0.00, 0.01, 0.05      | 0.0%, 0.0%, 0.1%  | 2% (64.1M)   | 0% (0B)    | 45%        | 0%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| etcd_z1/0 (15202d7d-4585-43fc-977c-67ee8a361248)*                          | running | n/a | medium_z1 | 192.168.0.133  | 0.02, 0.07, 0.06      | 0.1%, 0.1%, 1.4%  | 3% (105.8M)  | 0% (0B)    | 46%        | 1%         | 0%         |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| ha_proxy_z1/0 (816f5f75-313a-4b06-902f-afe4f39806f4)*                      | running | n/a | router_z1 | 192.168.0.125  | 0.00, 0.01, 0.05      | 0.1%, 0.2%, 0.2%  | 3% (102.4M)  | 0% (0B)    | 46%        | 1%         | 46%        |
|                                                                            |         |     |           | 10.251.207.205 |                       |                   |              |            |            |            |            |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| hm9000_z1/0 (06d6b54f-e506-4946-8b68-35eec12f04ce)*                        | running | n/a | medium_z1 | 192.168.0.105  | 0.00, 0.01, 0.05      | 0.0%, 0.1%, 0.1%  | 2% (64.2M)   | 0% (0B)    | 45%        | 0%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| loggregator_trafficcontroller_z1/0 (44e4a0c0-d8c1-42e5-a63f-df474fbf79b9)* | running | n/a | small_z1  | 192.168.0.108  | 0.00, 0.01, 0.04      | 0.0%, 0.0%, 0.0%  | 3% (53.8M)   | 0% (0B)    | 45%        | 0%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| nats_z1/0 (2291df6f-28a5-4161-9277-7bd31445c61e)*                          | running | n/a | medium_z1 | 192.168.0.127  | 0.00, 0.01, 0.05      | 0.1%, 0.1%, 0.1%  | 3% (106.7M)  | 0% (0B)    | 46%        | 1%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| postgres_z1/0 (ef5f3601-2a82-4757-b331-1e7f18c46266)*                      | running | n/a | medium_z1 | 192.168.0.129  | 0.00, 0.01, 0.05      | 0.0%, 0.1%, 0.1%  | 2% (91.1M)   | 0% (0B)    | 45%        | 0%         | 2%         |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| router_z1/0 (6af27034-7b92-446e-ba53-0b4f156d2c95)*                        | running | n/a | router_z1 | 192.168.0.130  | 0.00, 0.01, 0.05      | 0.0%, 0.1%, 0.1%  | 2% (64.1M)   | 0% (0B)    | 45%        | 0%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| runner_z1/0 (14143d1f-beee-4b2c-9f97-a8e26a7836ee)*                        | running | n/a | runner_z1 | 192.168.0.106  | 0.00, 0.01, 0.05      | 0.0%, 0.0%, 0.0%  | 1% (84.2M)   | 0% (0B)    | 45%        | 0%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| stats_z1/0 (344f9ddd-eea2-410d-b6ab-5e4daea6a99a)*                         | running | n/a | small_z1  | 192.168.0.101  | 0.00, 0.01, 0.05      | 0.1%, 0.1%, 0.2%  | 5% (106.6M)  | 0% (0B)    | 45%        | 2%         | n/a        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| uaa_z1/0 (1ded710a-7b5c-4181-bcc6-45d37986dc30)*                           | running | n/a | medium_z1 | 192.168.0.103  | 0.00, 0.01, 0.05      | 0.3%, 0.4%, 0.2%  | 11% (432.4M) | 0% (0B)    | 46%        | 2%         | 46%        |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+

(*) Bootstrap node

Instances total: 14
```

Thank you for support!!!

Br

Frantisek Dolezel

**Comment by jleavers** [comment]
Re: consul - have you seen this page?
https://docs.cloudfoundry.org/deploying/common/consul-security.html

This should help with the format - as shown you need to paste in the
contents of the certificate files, and provide an arbitrary value for the
encrypt_keys property.


On 21 June 2016 at 09:54:56, frantisek121 (notifications@github.com) wrote:

Hello,
I am trying to deploy cf on openstack kilo. I tried bosh stemcell 3232.4,
then I tried 3147 (because I have found that this version was working for
someone with similar problem). I use bosh 256.2 and bosh-openstack-cpi 24.
I am getting:

Started updating job api_z1 > api_z1/0
(8cdfa191-dd27-4759-9c6a-8c80efd4f240) (canary). Failed: 'api_z1/0
(8cdfa191-dd27-4759-9c6a-8c80efd4f240)' is not running after update. Review
logs for failed jobs: cloud_controller_ng, cloud_controller_worker_local_1,
cloud_controller_worker_local_2, nginx_cc, cloud_controller_worker_1
(00:11:00)
Error 400007: 'api_z1/0 (8cdfa191-dd27-4759-9c6a-8c80efd4f240)' is not
running after update. Review logs for failed jobs: cloud_controller_ng,
cloud_controller_worker_local_1, cloud_controller_worker_local_2, nginx_cc,
cloud_controller_worker_1

I have DNS server in my project, but it seems to me it works fine.
On failing api server:
root@fde841a <https://github.com/root/cf-release/commit/fde841a6>-9ec5-4166-a076-25b6cdfd9d7e:~#
ping somethingblabla.domain.com
PING somethingblabla.domain.com (10.251.207.205) 56(84) bytes of data.

10.251.207.205 - FIP for HA.

root@fde841a <https://github.com/root/cf-release/commit/fde841a6>-9ec5-4166-a076-25b6cdfd9d7e:~#
monit summary
The Monit daemon 5.2.4 uptime: 12m

Process 'cloud_controller_ng' not monitored
Process 'cloud_controller_worker_local_1' not monitored
Process 'cloud_controller_worker_local_2' not monitored
Process 'nginx_cc' not monitored
Process 'cloud_controller_migration' running
Process 'cloud_controller_clock' running
Process 'cloud_controller_worker_1' Does not exist
Process 'metron_agent' running
Process 'statsd-injector' running
Process 'route_registrar' running
System 'system_fde841a6-9ec5-4166-a076-25b6cdfd9d7e' running

I did check logs /var/vcap/sys/log/cloud_controller_ng/
cloud_controller_ng_ctl.err.log has a lot of lines like this:
------------ STARTING cloud_controller_ng_ctl at Tue Jun 21 08:28:42 UTC
2016 --------------

cloud_controller_ng_ctl.log:
------------ STARTING cloud_controller_ng_ctl at Tue Jun 21 08:29:29 UTC
2016 --------------
[2016-06-21 08:29:29+0000] Checking for blobstore availability
[2016-06-21 08:29:59+0000] Blobstore is not available

pre-start.stderr.log:
++ dirname /var/vcap/jobs/cloud_controller_ng/bin/pre-start

   - SCRIPT_DIR=/var/vcap/jobs/cloud_controller_ng/bin
   - source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh ++
   export PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
   ++ PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
   - app_domains=app.domain.com
   - system_domain=sys.domain.com
   - ruby
   /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb
   sys.domain.com app.domain.com
   - exit 0 ++ dirname /var/vcap/jobs/cloud_controller_ng/bin/pre-start
   - SCRIPT_DIR=/var/vcap/jobs/cloud_controller_ng/bin
   - source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh ++
   export PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
   ++ PATH=/var/vcap/packages/ruby-2.3/bin:/usr/sbin:/usr/bin:/sbin:/bin
   - app_domains=app.domain.com
   - system_domain=sys.domain.com
   - ruby
   /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb
   sys.domain.com app.domain.com
   - exit 0

There is "+ ruby
/var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb
sys.domain.com " - that makes me worried about my DNS settings, but still
wild card *domain.com gets resolved on all nodes.

I have noticed log "Blobstore is not available" so I checked blobstore_z1/0:
root@a5768e2 <https://github.com/root/cf-release/commit/a5768e2b>-87fd-4302-9c6d-3029fdfb98ca:~#
monit summary
The Monit daemon 5.2.4 uptime: 17h 13m

Process 'consul_agent' running
Process 'metron_agent' running
Process 'blobstore_nginx' running
Process 'blobstore_url_signer' running
Process 'route_registrar' running
System 'system_a5768e2b-87fd-4302-9c6d-3029fdfb98ca' running

root@a5768e2 <https://github.com/root/cf-release/commit/a5768e2b>-87fd-4302-9c6d-3029fdfb98ca:~#
ping bla.domain.com
PING bla.domain.com (10.251.207.205) 56(84) bytes of data.

I have recently posted a question to mail list to verify stub.yml file (not
answered) - I found documentation on this subject a little unclear, perhaps
because it should be obvious to most people. Just to check - is it ok to
use certs generated by generate-consul-certs like this? In config file I
would replace content of brackets with content of the files. Just for -
CONSUL_ENCRYPT_KEY ('') I am using ''" as empty string:

hm9000:
server_key: HM9000_SERVER_KEY (hm9000_server.key)
server_cert: HM9000_SERVER_CERT (hm9000_server.crt)
client_key: HM9000_CLIENT_KEY (hm9000_client.key)
client_cert: HM9000_CLIENT_CERT (hm9000_client.crt)
ca_cert: HM9000_CA_CERT (hm9000_ca.crt)

consul:
encrypt_keys:
- CONSUL_ENCRYPT_KEY ('')
ca_cert: CONSUL_CA_CERT (server-ca.crt)
server_cert: CONSUL_SERVER_CERT (server.crt)
server_key: CONSUL_SERVER_KEY (server.key)
agent_cert: CONSUL_AGENT_CERT (agent.crt)
agent_key: CONSUL_AGENT_KEY (agent.key)

tls:
port: 443
cert: BLOBSTORE_TLS_CERT (server.crt)
private_key: BLOBSTORE_PRIVATE_KEY (server.key)
ca_cert: BLOBSTORE_CA_CERT (server-ca.crt)
------------------------------

[root@cloudfoundry ~]# bosh instances --vitals
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on deployment 'openstack-prod' on 'my-bosh'

Director task 12

Task 12 done

+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| Instance | State | AZ | VM Type | IPs | Load | CPU % | Memory Usage |
Swap Usage | System | Ephemeral | Persistent |
| | | | | | (avg01, avg05, avg15) | (User, Sys, Wait) | | | Disk Usage |
Disk Usage | Disk Usage |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| api_z1/0 (8cdfa191-dd27-4759-9c6a-8c80efd4f240)* | failing | n/a |
large_z1 | 192.168.0.104 | 0.04, 0.06, 0.05 | 0.3%, 0.4%, 0.0% | 4%
(300.7M) | 0% (0B) | 46% | 2% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| blobstore_z1/0 (13444782-9086-471f-b5ab-4fc417ed227a)* | running | n/a |
medium_z1 | 192.168.0.102 | 0.00, 0.01, 0.05 | 0.1%, 0.2%, 0.1% | 3%
(106.7M) | 0% (0B) | 46% | 1% | 0% |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| consul_z1/0 (db7148d9-d5a0-41a1-9fc9-ac74712ace16)* | running | n/a |
small_z1 | 192.168.0.137 | 0.00, 0.01, 0.05 | 0.3%, 0.2%, 0.3% | 4% (81.8M)
| 0% (0B) | 46% | 1% | 0% |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| doppler_z1/0 (b1956f94-031e-4b25-abbc-4111ae9a6543)* | running | n/a |
medium_z1 | 192.168.0.107 | 0.00, 0.01, 0.05 | 0.0%, 0.0%, 0.1% | 2%
(64.1M) | 0% (0B) | 45% | 0% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| etcd_z1/0 (15202d7d-4585-43fc-977c-67ee8a361248)* | running | n/a |
medium_z1 | 192.168.0.133 | 0.02, 0.07, 0.06 | 0.1%, 0.1%, 1.4% | 3%
(105.8M) | 0% (0B) | 46% | 1% | 0% |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| ha_proxy_z1/0 (816f5f75-313a-4b06-902f-afe4f39806f4)* | running | n/a |
router_z1 | 192.168.0.125 | 0.00, 0.01, 0.05 | 0.1%, 0.2%, 0.2% | 3%
(102.4M) | 0% (0B) | 46% | 1% | 46% |
| | | | | 10.251.207.205 | | | | | | | |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| hm9000_z1/0 (06d6b54f-e506-4946-8b68-35eec12f04ce)* | running | n/a |
medium_z1 | 192.168.0.105 | 0.00, 0.01, 0.05 | 0.0%, 0.1%, 0.1% | 2%
(64.2M) | 0% (0B) | 45% | 0% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| loggregator_trafficcontroller_z1/0
(44e4a0c0-d8c1-42e5-a63f-df474fbf79b9)* | running | n/a | small_z1 |
192.168.0.108 | 0.00, 0.01, 0.04 | 0.0%, 0.0%, 0.0% | 3% (53.8M) | 0% (0B)
| 45% | 0% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| nats_z1/0 (2291df6f-28a5-4161-9277-7bd31445c61e)* | running | n/a |
medium_z1 | 192.168.0.127 | 0.00, 0.01, 0.05 | 0.1%, 0.1%, 0.1% | 3%
(106.7M) | 0% (0B) | 46% | 1% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| postgres_z1/0 (ef5f3601-2a82-4757-b331-1e7f18c46266)* | running | n/a |
medium_z1 | 192.168.0.129 | 0.00, 0.01, 0.05 | 0.0%, 0.1%, 0.1% | 2%
(91.1M) | 0% (0B) | 45% | 0% | 2% |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| router_z1/0 (6af27034-7b92-446e-ba53-0b4f156d2c95)* | running | n/a |
router_z1 | 192.168.0.130 | 0.00, 0.01, 0.05 | 0.0%, 0.1%, 0.1% | 2%
(64.1M) | 0% (0B) | 45% | 0% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| runner_z1/0 (14143d1f-beee-4b2c-9f97-a8e26a7836ee)* | running | n/a |
runner_z1 | 192.168.0.106 | 0.00, 0.01, 0.05 | 0.0%, 0.0%, 0.0% | 1%
(84.2M) | 0% (0B) | 45% | 0% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| stats_z1/0 (344f9ddd-eea2-410d-b6ab-5e4daea6a99a)* | running | n/a |
small_z1 | 192.168.0.101 | 0.00, 0.01, 0.05 | 0.1%, 0.1%, 0.2% | 5%
(106.6M) | 0% (0B) | 45% | 2% | n/a |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+
| uaa_z1/0 (1ded710a-7b5c-4181-bcc6-45d37986dc30)* | running | n/a |
medium_z1 | 192.168.0.103 | 0.00, 0.01, 0.05 | 0.3%, 0.4%, 0.2% | 11%
(432.4M) | 0% (0B) | 46% | 2% | 46% |
+----------------------------------------------------------------------------+---------+-----+-----------+----------------+-----------------------+-------------------+--------------+------------+------------+------------+------------+

(*) Bootstrap node

Instances total: 14
------------------------------

Thank you for support!!!

Br

Frantisek Dolezel

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudfoundry/cf-release/issues/985>, or mute the thread
<https://github.com/notifications/unsubscribe/ALTbiPJI9jbAml8G13vBEafmVUy6xJDoks5qN6bggaJpZM4I6f39>
.

**Comment by frantisek121** [comment]
Hi,

thank you for fast answer. Yes, I have seen it. However if you check that page or links from there like  https://github.com/square/certstrap or https://github.com/cloudfoundry/cf-release then you will see there is no info regarding "arbitrary value for the encrypt_keys property". 

I see in https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-consul-certs
certstrap --depot-path ${depot_path} init --passphrase '' --common-name consulCA

I believe you are refering to --passphrase '' - but it is set as empty string as default and there is no option to replace this unless to rewrite the code. But it should be usable as it is, right? 

Are you saying that I cannot use '' (as empty string) for RANDOM-SECRET-VALUE? If this is not passphrase and it is just some random value then my '' should work as well as anything else.

I appreciate your help, but I think if there would be problem with consul certificates I would not get so far. The part of my question you answering was more about reusing server certs for blobstore.

Frantisek

**Comment by Amit-PivotalLabs** [comment]
The line

```
+ ruby /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb sys.domain.com app.domain.com
```

is nothing to worry about, it's just running a pre-start check that the domains don't overlap.  You're fine, `sys.domain.com` and `app.domain.com` are considered valid for CC.

Your problem may be that the blobstore is unreachable, because CC may be expecting to reach the Blobstore via **internal** DNS managed by Consul, not your own DNS servers.  For this to work, the cloud controller needs to be colocated with the `consul_agent` so that it will be able to resolve internal DNS addresses.

If you have a section in your stub that looks like this: https://github.com/cloudfoundry/cf-release/blob/3290ed8d88cc453a013b77941d3960abe27b2317/spec/fixtures/openstack/cf-stub.yml#L155-L187, you can try removing it and see if that helps.

**Comment by frantisek121** [comment]
Yes, removing those lines helped, thank you. Can I do deployment without them, or will I miss some features/functionalities?

**Comment by Amit-PivotalLabs** [comment]
Nope, you should be fine.  Those stubs are out of date, we are waiting for one of our OpenStack test environments to be able to run CI against the OpenStack test stub.  I'll close out this issue for now, feel free to open a new one if you have further issues.

**Comment by cpraveen412** [comment]
Hello Amit and frantisek,
I got the same issue in vsphere. But I do not have the lines mentioned by Amit. could anyone help me?

Thanks

**Comment by frantisek121** [comment]
Hi cpraveen412,

it is hard to say what is wrong, this error may be caused by several issues. You need to create new issue and provide details from logs and your configuration. I am sure someone will help you.

**Comment by cpraveen412** [comment]
sure. thanks.
