### ISSUE TITLE
Consul server cert needs a specific CN setting

### ISSUE THREAD

**Issue by dcarissi** [cloudfoundry/cf-release#993]
I'm trying to create my own ca/crt/key files for consul and eventually HM9000, DEA and UAA.  It looks to me like the consul server.crt file needs a specific setting of CN=server.dc1.cf.internal .  I can't find any documentation on why this is or how the code checks for this particular string.

Can someone please point me to the correct docs or provide an answer here?
Thanks

ps. I've tried the CloudFoundry Slack app but not getting any responses...

**Comment by zankich** [comment]
The CN requirements for your server certificate are a combination of your [datacenter](https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/spec#L36) and your [domain](https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/spec#L48).

The consul documentation for [TLS encryption](https://www.consul.io/docs/agent/encryption.html) state that 
```
If verify_server_hostname is set, then outgoing connections perform 
hostname verification. All servers must have a certificate valid 
for "server.<datacenter>.<domain>" or the client will reject the handshake. 
```

This requirement should be described in the consul-release README for easier reference.

Thanks for bringing this issue to our attention.

**Comment by dcarissi** [comment]
Thanks for the reply.  Follow up question, are there similar requirements for HM9000, DEA and UAA??
I noticed that the dea server certificate has Subject: CN=dea.service.cf.internal, HM9000 server certificate has Subject: CN=listener-hm9000.service.cf.internal .... so are those also required??

**Comment by zankich** [comment]
Yes those are required because those components use consul internally for service discovery, using the same scheme which was used to configure the consul servers. 

When a job registers a service with consul, it follows the format `<service-name>.service.<consul domain>`. In the case of DEA it is `dea.service.cf.internal`. So if you want to sign a certificate for an internal API server, it needs to be signed to the consul generated service name.

Keep in mind that many jobs have `cf.internal` hardcoded in their scripts, so changing the domain for your consul server is not recommended.

**Comment by zankich** [comment]
@dcarissi added a note in the consul README about common name requirements, https://github.com/cloudfoundry-incubator/consul-release/commit/c199f9ede829be8830cab588f745558d43d405eb

**Comment by zankich** [comment]
If you have any further questions please feel free to ask.

**Comment by ryansmithevans** [comment]
The amendment to the README is an improvement. However, it does mention that this is the config by default.

I'm still having trouble finding how to configure this. Is there even a way? Does the README need to be extended to show how this could be done?
